/*
 * generated by Xtext 2.15.0
 */
package de.ubt.ai1.m2m.bxtenddsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class BXtendDSLRuntimeModule extends AbstractBXtendDSLRuntimeModule {
}
