/**
 * generated by Xtext 2.16.0
 */
package de.ubt.ai1.m2m.bxtenddsl.bXtendDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.BXtendDSLFactory
 * @model kind="package"
 * @generated
 */
public interface BXtendDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "bXtendDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ubt.de/ai1/m2m/bxtenddsl/BXtendDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "bXtendDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BXtendDSLPackage eINSTANCE = de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLImpl <em>BXtend DSL</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLImpl
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getBXtendDSL()
   * @generated
   */
  int BXTEND_DSL = 0;

  /**
   * The feature id for the '<em><b>Metamodels</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BXTEND_DSL__METAMODELS = 0;

  /**
   * The feature id for the '<em><b>Config</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BXTEND_DSL__CONFIG = 1;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BXTEND_DSL__RULES = 2;

  /**
   * The number of structural features of the '<em>BXtend DSL</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BXTEND_DSL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.MetamodelsImpl <em>Metamodels</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.MetamodelsImpl
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getMetamodels()
   * @generated
   */
  int METAMODELS = 1;

  /**
   * The feature id for the '<em><b>Sourcemodel</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METAMODELS__SOURCEMODEL = 0;

  /**
   * The feature id for the '<em><b>Customized Src Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METAMODELS__CUSTOMIZED_SRC_ELEMENTS = 1;

  /**
   * The feature id for the '<em><b>Targetmodel</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METAMODELS__TARGETMODEL = 2;

  /**
   * The feature id for the '<em><b>Customized Trg Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METAMODELS__CUSTOMIZED_TRG_ELEMENTS = 3;

  /**
   * The number of structural features of the '<em>Metamodels</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METAMODELS_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.CustomizedElementImpl <em>Customized Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.CustomizedElementImpl
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getCustomizedElement()
   * @generated
   */
  int CUSTOMIZED_ELEMENT = 2;

  /**
   * The feature id for the '<em><b>Element</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOMIZED_ELEMENT__ELEMENT = 0;

  /**
   * The feature id for the '<em><b>Custom Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOMIZED_ELEMENT__CUSTOM_ID = 1;

  /**
   * The number of structural features of the '<em>Customized Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOMIZED_ELEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.CustomizedGetterImpl <em>Customized Getter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.CustomizedGetterImpl
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getCustomizedGetter()
   * @generated
   */
  int CUSTOMIZED_GETTER = 3;

  /**
   * The feature id for the '<em><b>Element</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOMIZED_GETTER__ELEMENT = CUSTOMIZED_ELEMENT__ELEMENT;

  /**
   * The feature id for the '<em><b>Custom Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOMIZED_GETTER__CUSTOM_ID = CUSTOMIZED_ELEMENT__CUSTOM_ID;

  /**
   * The number of structural features of the '<em>Customized Getter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOMIZED_GETTER_FEATURE_COUNT = CUSTOMIZED_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.CustomizedSetterImpl <em>Customized Setter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.CustomizedSetterImpl
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getCustomizedSetter()
   * @generated
   */
  int CUSTOMIZED_SETTER = 4;

  /**
   * The feature id for the '<em><b>Element</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOMIZED_SETTER__ELEMENT = CUSTOMIZED_ELEMENT__ELEMENT;

  /**
   * The feature id for the '<em><b>Custom Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOMIZED_SETTER__CUSTOM_ID = CUSTOMIZED_ELEMENT__CUSTOM_ID;

  /**
   * The number of structural features of the '<em>Customized Setter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOMIZED_SETTER_FEATURE_COUNT = CUSTOMIZED_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.ConfigImpl <em>Config</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.ConfigImpl
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getConfig()
   * @generated
   */
  int CONFIG = 5;

  /**
   * The feature id for the '<em><b>Options</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG__OPTIONS = 0;

  /**
   * The number of structural features of the '<em>Config</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.TransformationRuleImpl <em>Transformation Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.TransformationRuleImpl
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getTransformationRule()
   * @generated
   */
  int TRANSFORMATION_RULE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSFORMATION_RULE__NAME = 0;

  /**
   * The feature id for the '<em><b>Src Matcher</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSFORMATION_RULE__SRC_MATCHER = 1;

  /**
   * The feature id for the '<em><b>Trg Matcher</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSFORMATION_RULE__TRG_MATCHER = 2;

  /**
   * The feature id for the '<em><b>Mappings</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSFORMATION_RULE__MAPPINGS = 3;

  /**
   * The number of structural features of the '<em>Transformation Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSFORMATION_RULE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.ClassMatcherImpl <em>Class Matcher</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.ClassMatcherImpl
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getClassMatcher()
   * @generated
   */
  int CLASS_MATCHER = 7;

  /**
   * The feature id for the '<em><b>Clazz</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_MATCHER__CLAZZ = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_MATCHER__NAME = 1;

  /**
   * The feature id for the '<em><b>Modifier</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_MATCHER__MODIFIER = 2;

  /**
   * The number of structural features of the '<em>Class Matcher</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_MATCHER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.SrcClassMatcherImpl <em>Src Class Matcher</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.SrcClassMatcherImpl
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getSrcClassMatcher()
   * @generated
   */
  int SRC_CLASS_MATCHER = 8;

  /**
   * The feature id for the '<em><b>Clazz</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SRC_CLASS_MATCHER__CLAZZ = CLASS_MATCHER__CLAZZ;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SRC_CLASS_MATCHER__NAME = CLASS_MATCHER__NAME;

  /**
   * The feature id for the '<em><b>Modifier</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SRC_CLASS_MATCHER__MODIFIER = CLASS_MATCHER__MODIFIER;

  /**
   * The number of structural features of the '<em>Src Class Matcher</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SRC_CLASS_MATCHER_FEATURE_COUNT = CLASS_MATCHER_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.TrgClassMatcherImpl <em>Trg Class Matcher</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.TrgClassMatcherImpl
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getTrgClassMatcher()
   * @generated
   */
  int TRG_CLASS_MATCHER = 9;

  /**
   * The feature id for the '<em><b>Clazz</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRG_CLASS_MATCHER__CLAZZ = CLASS_MATCHER__CLAZZ;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRG_CLASS_MATCHER__NAME = CLASS_MATCHER__NAME;

  /**
   * The feature id for the '<em><b>Modifier</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRG_CLASS_MATCHER__MODIFIER = CLASS_MATCHER__MODIFIER;

  /**
   * The number of structural features of the '<em>Trg Class Matcher</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRG_CLASS_MATCHER_FEATURE_COUNT = CLASS_MATCHER_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.ClassMatcherModifierImpl <em>Class Matcher Modifier</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.ClassMatcherModifierImpl
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getClassMatcherModifier()
   * @generated
   */
  int CLASS_MATCHER_MODIFIER = 10;

  /**
   * The feature id for the '<em><b>Filter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_MATCHER_MODIFIER__FILTER = 0;

  /**
   * The feature id for the '<em><b>Sort</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_MATCHER_MODIFIER__SORT = 1;

  /**
   * The feature id for the '<em><b>Creation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_MATCHER_MODIFIER__CREATION = 2;

  /**
   * The feature id for the '<em><b>Deletion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_MATCHER_MODIFIER__DELETION = 3;

  /**
   * The feature id for the '<em><b>Group</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_MATCHER_MODIFIER__GROUP = 4;

  /**
   * The number of structural features of the '<em>Class Matcher Modifier</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_MATCHER_MODIFIER_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.FeatureMappingImpl <em>Feature Mapping</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.FeatureMappingImpl
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getFeatureMapping()
   * @generated
   */
  int FEATURE_MAPPING = 11;

  /**
   * The feature id for the '<em><b>Src Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_MAPPING__SRC_FEATURES = 0;

  /**
   * The feature id for the '<em><b>Src Classes</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_MAPPING__SRC_CLASSES = 1;

  /**
   * The feature id for the '<em><b>Direction</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_MAPPING__DIRECTION = 2;

  /**
   * The feature id for the '<em><b>Trg Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_MAPPING__TRG_FEATURES = 3;

  /**
   * The feature id for the '<em><b>Trg Classes</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_MAPPING__TRG_CLASSES = 4;

  /**
   * The number of structural features of the '<em>Feature Mapping</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURE_MAPPING_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.MappingFeatureImpl <em>Mapping Feature</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.MappingFeatureImpl
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getMappingFeature()
   * @generated
   */
  int MAPPING_FEATURE = 12;

  /**
   * The feature id for the '<em><b>Feature</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAPPING_FEATURE__FEATURE = 0;

  /**
   * The feature id for the '<em><b>Corr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAPPING_FEATURE__CORR = 1;

  /**
   * The feature id for the '<em><b>Corrs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAPPING_FEATURE__CORRS = 2;

  /**
   * The number of structural features of the '<em>Mapping Feature</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAPPING_FEATURE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.SrcMappingFeatureImpl <em>Src Mapping Feature</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.SrcMappingFeatureImpl
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getSrcMappingFeature()
   * @generated
   */
  int SRC_MAPPING_FEATURE = 13;

  /**
   * The feature id for the '<em><b>Feature</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SRC_MAPPING_FEATURE__FEATURE = MAPPING_FEATURE__FEATURE;

  /**
   * The feature id for the '<em><b>Corr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SRC_MAPPING_FEATURE__CORR = MAPPING_FEATURE__CORR;

  /**
   * The feature id for the '<em><b>Corrs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SRC_MAPPING_FEATURE__CORRS = MAPPING_FEATURE__CORRS;

  /**
   * The number of structural features of the '<em>Src Mapping Feature</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SRC_MAPPING_FEATURE_FEATURE_COUNT = MAPPING_FEATURE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.TrgMappingFeatureImpl <em>Trg Mapping Feature</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.TrgMappingFeatureImpl
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getTrgMappingFeature()
   * @generated
   */
  int TRG_MAPPING_FEATURE = 14;

  /**
   * The feature id for the '<em><b>Feature</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRG_MAPPING_FEATURE__FEATURE = MAPPING_FEATURE__FEATURE;

  /**
   * The feature id for the '<em><b>Corr</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRG_MAPPING_FEATURE__CORR = MAPPING_FEATURE__CORR;

  /**
   * The feature id for the '<em><b>Corrs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRG_MAPPING_FEATURE__CORRS = MAPPING_FEATURE__CORRS;

  /**
   * The number of structural features of the '<em>Trg Mapping Feature</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRG_MAPPING_FEATURE_FEATURE_COUNT = MAPPING_FEATURE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.CorrespondenceImpl <em>Correspondence</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.CorrespondenceImpl
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getCorrespondence()
   * @generated
   */
  int CORRESPONDENCE = 15;

  /**
   * The feature id for the '<em><b>Rule</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CORRESPONDENCE__RULE = 0;

  /**
   * The feature id for the '<em><b>Matchers</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CORRESPONDENCE__MATCHERS = 1;

  /**
   * The number of structural features of the '<em>Correspondence</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CORRESPONDENCE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.Direction <em>Direction</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.Direction
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getDirection()
   * @generated
   */
  int DIRECTION = 16;


  /**
   * Returns the meta object for class '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.BXtendDSL <em>BXtend DSL</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>BXtend DSL</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.BXtendDSL
   * @generated
   */
  EClass getBXtendDSL();

  /**
   * Returns the meta object for the containment reference '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.BXtendDSL#getMetamodels <em>Metamodels</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Metamodels</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.BXtendDSL#getMetamodels()
   * @see #getBXtendDSL()
   * @generated
   */
  EReference getBXtendDSL_Metamodels();

  /**
   * Returns the meta object for the containment reference '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.BXtendDSL#getConfig <em>Config</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Config</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.BXtendDSL#getConfig()
   * @see #getBXtendDSL()
   * @generated
   */
  EReference getBXtendDSL_Config();

  /**
   * Returns the meta object for the containment reference list '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.BXtendDSL#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rules</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.BXtendDSL#getRules()
   * @see #getBXtendDSL()
   * @generated
   */
  EReference getBXtendDSL_Rules();

  /**
   * Returns the meta object for class '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.Metamodels <em>Metamodels</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Metamodels</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.Metamodels
   * @generated
   */
  EClass getMetamodels();

  /**
   * Returns the meta object for the attribute '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.Metamodels#getSourcemodel <em>Sourcemodel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sourcemodel</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.Metamodels#getSourcemodel()
   * @see #getMetamodels()
   * @generated
   */
  EAttribute getMetamodels_Sourcemodel();

  /**
   * Returns the meta object for the containment reference list '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.Metamodels#getCustomizedSrcElements <em>Customized Src Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Customized Src Elements</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.Metamodels#getCustomizedSrcElements()
   * @see #getMetamodels()
   * @generated
   */
  EReference getMetamodels_CustomizedSrcElements();

  /**
   * Returns the meta object for the attribute '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.Metamodels#getTargetmodel <em>Targetmodel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Targetmodel</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.Metamodels#getTargetmodel()
   * @see #getMetamodels()
   * @generated
   */
  EAttribute getMetamodels_Targetmodel();

  /**
   * Returns the meta object for the containment reference list '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.Metamodels#getCustomizedTrgElements <em>Customized Trg Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Customized Trg Elements</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.Metamodels#getCustomizedTrgElements()
   * @see #getMetamodels()
   * @generated
   */
  EReference getMetamodels_CustomizedTrgElements();

  /**
   * Returns the meta object for class '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.CustomizedElement <em>Customized Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Customized Element</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.CustomizedElement
   * @generated
   */
  EClass getCustomizedElement();

  /**
   * Returns the meta object for the reference '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.CustomizedElement#getElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Element</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.CustomizedElement#getElement()
   * @see #getCustomizedElement()
   * @generated
   */
  EReference getCustomizedElement_Element();

  /**
   * Returns the meta object for the attribute '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.CustomizedElement#getCustomId <em>Custom Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Custom Id</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.CustomizedElement#getCustomId()
   * @see #getCustomizedElement()
   * @generated
   */
  EAttribute getCustomizedElement_CustomId();

  /**
   * Returns the meta object for class '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.CustomizedGetter <em>Customized Getter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Customized Getter</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.CustomizedGetter
   * @generated
   */
  EClass getCustomizedGetter();

  /**
   * Returns the meta object for class '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.CustomizedSetter <em>Customized Setter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Customized Setter</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.CustomizedSetter
   * @generated
   */
  EClass getCustomizedSetter();

  /**
   * Returns the meta object for class '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.Config <em>Config</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Config</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.Config
   * @generated
   */
  EClass getConfig();

  /**
   * Returns the meta object for the attribute list '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.Config#getOptions <em>Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Options</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.Config#getOptions()
   * @see #getConfig()
   * @generated
   */
  EAttribute getConfig_Options();

  /**
   * Returns the meta object for class '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.TransformationRule <em>Transformation Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transformation Rule</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.TransformationRule
   * @generated
   */
  EClass getTransformationRule();

  /**
   * Returns the meta object for the attribute '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.TransformationRule#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.TransformationRule#getName()
   * @see #getTransformationRule()
   * @generated
   */
  EAttribute getTransformationRule_Name();

  /**
   * Returns the meta object for the containment reference list '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.TransformationRule#getSrcMatcher <em>Src Matcher</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Src Matcher</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.TransformationRule#getSrcMatcher()
   * @see #getTransformationRule()
   * @generated
   */
  EReference getTransformationRule_SrcMatcher();

  /**
   * Returns the meta object for the containment reference list '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.TransformationRule#getTrgMatcher <em>Trg Matcher</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Trg Matcher</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.TransformationRule#getTrgMatcher()
   * @see #getTransformationRule()
   * @generated
   */
  EReference getTransformationRule_TrgMatcher();

  /**
   * Returns the meta object for the containment reference list '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.TransformationRule#getMappings <em>Mappings</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Mappings</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.TransformationRule#getMappings()
   * @see #getTransformationRule()
   * @generated
   */
  EReference getTransformationRule_Mappings();

  /**
   * Returns the meta object for class '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.ClassMatcher <em>Class Matcher</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class Matcher</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.ClassMatcher
   * @generated
   */
  EClass getClassMatcher();

  /**
   * Returns the meta object for the reference '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.ClassMatcher#getClazz <em>Clazz</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Clazz</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.ClassMatcher#getClazz()
   * @see #getClassMatcher()
   * @generated
   */
  EReference getClassMatcher_Clazz();

  /**
   * Returns the meta object for the attribute '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.ClassMatcher#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.ClassMatcher#getName()
   * @see #getClassMatcher()
   * @generated
   */
  EAttribute getClassMatcher_Name();

  /**
   * Returns the meta object for the containment reference '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.ClassMatcher#getModifier <em>Modifier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Modifier</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.ClassMatcher#getModifier()
   * @see #getClassMatcher()
   * @generated
   */
  EReference getClassMatcher_Modifier();

  /**
   * Returns the meta object for class '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.SrcClassMatcher <em>Src Class Matcher</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Src Class Matcher</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.SrcClassMatcher
   * @generated
   */
  EClass getSrcClassMatcher();

  /**
   * Returns the meta object for class '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.TrgClassMatcher <em>Trg Class Matcher</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trg Class Matcher</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.TrgClassMatcher
   * @generated
   */
  EClass getTrgClassMatcher();

  /**
   * Returns the meta object for class '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.ClassMatcherModifier <em>Class Matcher Modifier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class Matcher Modifier</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.ClassMatcherModifier
   * @generated
   */
  EClass getClassMatcherModifier();

  /**
   * Returns the meta object for the attribute '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.ClassMatcherModifier#isFilter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Filter</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.ClassMatcherModifier#isFilter()
   * @see #getClassMatcherModifier()
   * @generated
   */
  EAttribute getClassMatcherModifier_Filter();

  /**
   * Returns the meta object for the attribute '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.ClassMatcherModifier#isSort <em>Sort</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sort</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.ClassMatcherModifier#isSort()
   * @see #getClassMatcherModifier()
   * @generated
   */
  EAttribute getClassMatcherModifier_Sort();

  /**
   * Returns the meta object for the attribute '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.ClassMatcherModifier#isCreation <em>Creation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Creation</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.ClassMatcherModifier#isCreation()
   * @see #getClassMatcherModifier()
   * @generated
   */
  EAttribute getClassMatcherModifier_Creation();

  /**
   * Returns the meta object for the attribute '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.ClassMatcherModifier#isDeletion <em>Deletion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Deletion</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.ClassMatcherModifier#isDeletion()
   * @see #getClassMatcherModifier()
   * @generated
   */
  EAttribute getClassMatcherModifier_Deletion();

  /**
   * Returns the meta object for the attribute '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.ClassMatcherModifier#isGroup <em>Group</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Group</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.ClassMatcherModifier#isGroup()
   * @see #getClassMatcherModifier()
   * @generated
   */
  EAttribute getClassMatcherModifier_Group();

  /**
   * Returns the meta object for class '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.FeatureMapping <em>Feature Mapping</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Feature Mapping</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.FeatureMapping
   * @generated
   */
  EClass getFeatureMapping();

  /**
   * Returns the meta object for the containment reference list '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.FeatureMapping#getSrcFeatures <em>Src Features</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Src Features</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.FeatureMapping#getSrcFeatures()
   * @see #getFeatureMapping()
   * @generated
   */
  EReference getFeatureMapping_SrcFeatures();

  /**
   * Returns the meta object for the reference list '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.FeatureMapping#getSrcClasses <em>Src Classes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Src Classes</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.FeatureMapping#getSrcClasses()
   * @see #getFeatureMapping()
   * @generated
   */
  EReference getFeatureMapping_SrcClasses();

  /**
   * Returns the meta object for the attribute '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.FeatureMapping#getDirection <em>Direction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Direction</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.FeatureMapping#getDirection()
   * @see #getFeatureMapping()
   * @generated
   */
  EAttribute getFeatureMapping_Direction();

  /**
   * Returns the meta object for the containment reference list '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.FeatureMapping#getTrgFeatures <em>Trg Features</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Trg Features</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.FeatureMapping#getTrgFeatures()
   * @see #getFeatureMapping()
   * @generated
   */
  EReference getFeatureMapping_TrgFeatures();

  /**
   * Returns the meta object for the reference list '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.FeatureMapping#getTrgClasses <em>Trg Classes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Trg Classes</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.FeatureMapping#getTrgClasses()
   * @see #getFeatureMapping()
   * @generated
   */
  EReference getFeatureMapping_TrgClasses();

  /**
   * Returns the meta object for class '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.MappingFeature <em>Mapping Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mapping Feature</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.MappingFeature
   * @generated
   */
  EClass getMappingFeature();

  /**
   * Returns the meta object for the reference '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.MappingFeature#getFeature <em>Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Feature</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.MappingFeature#getFeature()
   * @see #getMappingFeature()
   * @generated
   */
  EReference getMappingFeature_Feature();

  /**
   * Returns the meta object for the attribute '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.MappingFeature#isCorr <em>Corr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Corr</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.MappingFeature#isCorr()
   * @see #getMappingFeature()
   * @generated
   */
  EAttribute getMappingFeature_Corr();

  /**
   * Returns the meta object for the containment reference list '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.MappingFeature#getCorrs <em>Corrs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Corrs</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.MappingFeature#getCorrs()
   * @see #getMappingFeature()
   * @generated
   */
  EReference getMappingFeature_Corrs();

  /**
   * Returns the meta object for class '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.SrcMappingFeature <em>Src Mapping Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Src Mapping Feature</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.SrcMappingFeature
   * @generated
   */
  EClass getSrcMappingFeature();

  /**
   * Returns the meta object for class '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.TrgMappingFeature <em>Trg Mapping Feature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trg Mapping Feature</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.TrgMappingFeature
   * @generated
   */
  EClass getTrgMappingFeature();

  /**
   * Returns the meta object for class '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.Correspondence <em>Correspondence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Correspondence</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.Correspondence
   * @generated
   */
  EClass getCorrespondence();

  /**
   * Returns the meta object for the reference '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.Correspondence#getRule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Rule</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.Correspondence#getRule()
   * @see #getCorrespondence()
   * @generated
   */
  EReference getCorrespondence_Rule();

  /**
   * Returns the meta object for the reference list '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.Correspondence#getMatchers <em>Matchers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Matchers</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.Correspondence#getMatchers()
   * @see #getCorrespondence()
   * @generated
   */
  EReference getCorrespondence_Matchers();

  /**
   * Returns the meta object for enum '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.Direction <em>Direction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Direction</em>'.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.Direction
   * @generated
   */
  EEnum getDirection();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BXtendDSLFactory getBXtendDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLImpl <em>BXtend DSL</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLImpl
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getBXtendDSL()
     * @generated
     */
    EClass BXTEND_DSL = eINSTANCE.getBXtendDSL();

    /**
     * The meta object literal for the '<em><b>Metamodels</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BXTEND_DSL__METAMODELS = eINSTANCE.getBXtendDSL_Metamodels();

    /**
     * The meta object literal for the '<em><b>Config</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BXTEND_DSL__CONFIG = eINSTANCE.getBXtendDSL_Config();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BXTEND_DSL__RULES = eINSTANCE.getBXtendDSL_Rules();

    /**
     * The meta object literal for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.MetamodelsImpl <em>Metamodels</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.MetamodelsImpl
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getMetamodels()
     * @generated
     */
    EClass METAMODELS = eINSTANCE.getMetamodels();

    /**
     * The meta object literal for the '<em><b>Sourcemodel</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METAMODELS__SOURCEMODEL = eINSTANCE.getMetamodels_Sourcemodel();

    /**
     * The meta object literal for the '<em><b>Customized Src Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METAMODELS__CUSTOMIZED_SRC_ELEMENTS = eINSTANCE.getMetamodels_CustomizedSrcElements();

    /**
     * The meta object literal for the '<em><b>Targetmodel</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METAMODELS__TARGETMODEL = eINSTANCE.getMetamodels_Targetmodel();

    /**
     * The meta object literal for the '<em><b>Customized Trg Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference METAMODELS__CUSTOMIZED_TRG_ELEMENTS = eINSTANCE.getMetamodels_CustomizedTrgElements();

    /**
     * The meta object literal for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.CustomizedElementImpl <em>Customized Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.CustomizedElementImpl
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getCustomizedElement()
     * @generated
     */
    EClass CUSTOMIZED_ELEMENT = eINSTANCE.getCustomizedElement();

    /**
     * The meta object literal for the '<em><b>Element</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CUSTOMIZED_ELEMENT__ELEMENT = eINSTANCE.getCustomizedElement_Element();

    /**
     * The meta object literal for the '<em><b>Custom Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CUSTOMIZED_ELEMENT__CUSTOM_ID = eINSTANCE.getCustomizedElement_CustomId();

    /**
     * The meta object literal for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.CustomizedGetterImpl <em>Customized Getter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.CustomizedGetterImpl
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getCustomizedGetter()
     * @generated
     */
    EClass CUSTOMIZED_GETTER = eINSTANCE.getCustomizedGetter();

    /**
     * The meta object literal for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.CustomizedSetterImpl <em>Customized Setter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.CustomizedSetterImpl
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getCustomizedSetter()
     * @generated
     */
    EClass CUSTOMIZED_SETTER = eINSTANCE.getCustomizedSetter();

    /**
     * The meta object literal for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.ConfigImpl <em>Config</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.ConfigImpl
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getConfig()
     * @generated
     */
    EClass CONFIG = eINSTANCE.getConfig();

    /**
     * The meta object literal for the '<em><b>Options</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIG__OPTIONS = eINSTANCE.getConfig_Options();

    /**
     * The meta object literal for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.TransformationRuleImpl <em>Transformation Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.TransformationRuleImpl
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getTransformationRule()
     * @generated
     */
    EClass TRANSFORMATION_RULE = eINSTANCE.getTransformationRule();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSFORMATION_RULE__NAME = eINSTANCE.getTransformationRule_Name();

    /**
     * The meta object literal for the '<em><b>Src Matcher</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSFORMATION_RULE__SRC_MATCHER = eINSTANCE.getTransformationRule_SrcMatcher();

    /**
     * The meta object literal for the '<em><b>Trg Matcher</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSFORMATION_RULE__TRG_MATCHER = eINSTANCE.getTransformationRule_TrgMatcher();

    /**
     * The meta object literal for the '<em><b>Mappings</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSFORMATION_RULE__MAPPINGS = eINSTANCE.getTransformationRule_Mappings();

    /**
     * The meta object literal for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.ClassMatcherImpl <em>Class Matcher</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.ClassMatcherImpl
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getClassMatcher()
     * @generated
     */
    EClass CLASS_MATCHER = eINSTANCE.getClassMatcher();

    /**
     * The meta object literal for the '<em><b>Clazz</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS_MATCHER__CLAZZ = eINSTANCE.getClassMatcher_Clazz();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLASS_MATCHER__NAME = eINSTANCE.getClassMatcher_Name();

    /**
     * The meta object literal for the '<em><b>Modifier</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS_MATCHER__MODIFIER = eINSTANCE.getClassMatcher_Modifier();

    /**
     * The meta object literal for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.SrcClassMatcherImpl <em>Src Class Matcher</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.SrcClassMatcherImpl
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getSrcClassMatcher()
     * @generated
     */
    EClass SRC_CLASS_MATCHER = eINSTANCE.getSrcClassMatcher();

    /**
     * The meta object literal for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.TrgClassMatcherImpl <em>Trg Class Matcher</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.TrgClassMatcherImpl
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getTrgClassMatcher()
     * @generated
     */
    EClass TRG_CLASS_MATCHER = eINSTANCE.getTrgClassMatcher();

    /**
     * The meta object literal for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.ClassMatcherModifierImpl <em>Class Matcher Modifier</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.ClassMatcherModifierImpl
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getClassMatcherModifier()
     * @generated
     */
    EClass CLASS_MATCHER_MODIFIER = eINSTANCE.getClassMatcherModifier();

    /**
     * The meta object literal for the '<em><b>Filter</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLASS_MATCHER_MODIFIER__FILTER = eINSTANCE.getClassMatcherModifier_Filter();

    /**
     * The meta object literal for the '<em><b>Sort</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLASS_MATCHER_MODIFIER__SORT = eINSTANCE.getClassMatcherModifier_Sort();

    /**
     * The meta object literal for the '<em><b>Creation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLASS_MATCHER_MODIFIER__CREATION = eINSTANCE.getClassMatcherModifier_Creation();

    /**
     * The meta object literal for the '<em><b>Deletion</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLASS_MATCHER_MODIFIER__DELETION = eINSTANCE.getClassMatcherModifier_Deletion();

    /**
     * The meta object literal for the '<em><b>Group</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLASS_MATCHER_MODIFIER__GROUP = eINSTANCE.getClassMatcherModifier_Group();

    /**
     * The meta object literal for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.FeatureMappingImpl <em>Feature Mapping</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.FeatureMappingImpl
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getFeatureMapping()
     * @generated
     */
    EClass FEATURE_MAPPING = eINSTANCE.getFeatureMapping();

    /**
     * The meta object literal for the '<em><b>Src Features</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FEATURE_MAPPING__SRC_FEATURES = eINSTANCE.getFeatureMapping_SrcFeatures();

    /**
     * The meta object literal for the '<em><b>Src Classes</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FEATURE_MAPPING__SRC_CLASSES = eINSTANCE.getFeatureMapping_SrcClasses();

    /**
     * The meta object literal for the '<em><b>Direction</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FEATURE_MAPPING__DIRECTION = eINSTANCE.getFeatureMapping_Direction();

    /**
     * The meta object literal for the '<em><b>Trg Features</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FEATURE_MAPPING__TRG_FEATURES = eINSTANCE.getFeatureMapping_TrgFeatures();

    /**
     * The meta object literal for the '<em><b>Trg Classes</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FEATURE_MAPPING__TRG_CLASSES = eINSTANCE.getFeatureMapping_TrgClasses();

    /**
     * The meta object literal for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.MappingFeatureImpl <em>Mapping Feature</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.MappingFeatureImpl
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getMappingFeature()
     * @generated
     */
    EClass MAPPING_FEATURE = eINSTANCE.getMappingFeature();

    /**
     * The meta object literal for the '<em><b>Feature</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAPPING_FEATURE__FEATURE = eINSTANCE.getMappingFeature_Feature();

    /**
     * The meta object literal for the '<em><b>Corr</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAPPING_FEATURE__CORR = eINSTANCE.getMappingFeature_Corr();

    /**
     * The meta object literal for the '<em><b>Corrs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAPPING_FEATURE__CORRS = eINSTANCE.getMappingFeature_Corrs();

    /**
     * The meta object literal for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.SrcMappingFeatureImpl <em>Src Mapping Feature</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.SrcMappingFeatureImpl
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getSrcMappingFeature()
     * @generated
     */
    EClass SRC_MAPPING_FEATURE = eINSTANCE.getSrcMappingFeature();

    /**
     * The meta object literal for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.TrgMappingFeatureImpl <em>Trg Mapping Feature</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.TrgMappingFeatureImpl
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getTrgMappingFeature()
     * @generated
     */
    EClass TRG_MAPPING_FEATURE = eINSTANCE.getTrgMappingFeature();

    /**
     * The meta object literal for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.CorrespondenceImpl <em>Correspondence</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.CorrespondenceImpl
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getCorrespondence()
     * @generated
     */
    EClass CORRESPONDENCE = eINSTANCE.getCorrespondence();

    /**
     * The meta object literal for the '<em><b>Rule</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CORRESPONDENCE__RULE = eINSTANCE.getCorrespondence_Rule();

    /**
     * The meta object literal for the '<em><b>Matchers</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CORRESPONDENCE__MATCHERS = eINSTANCE.getCorrespondence_Matchers();

    /**
     * The meta object literal for the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.Direction <em>Direction</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.Direction
     * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLPackageImpl#getDirection()
     * @generated
     */
    EEnum DIRECTION = eINSTANCE.getDirection();

  }

} //BXtendDSLPackage
