/**
 * generated by Xtext 2.16.0
 */
package de.ubt.ai1.m2m.bxtenddsl.bXtendDSL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.BXtendDSLPackage
 * @generated
 */
public interface BXtendDSLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BXtendDSLFactory eINSTANCE = de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.BXtendDSLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>BXtend DSL</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>BXtend DSL</em>'.
   * @generated
   */
  BXtendDSL createBXtendDSL();

  /**
   * Returns a new object of class '<em>Metamodels</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Metamodels</em>'.
   * @generated
   */
  Metamodels createMetamodels();

  /**
   * Returns a new object of class '<em>Customized Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Customized Element</em>'.
   * @generated
   */
  CustomizedElement createCustomizedElement();

  /**
   * Returns a new object of class '<em>Customized Getter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Customized Getter</em>'.
   * @generated
   */
  CustomizedGetter createCustomizedGetter();

  /**
   * Returns a new object of class '<em>Customized Setter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Customized Setter</em>'.
   * @generated
   */
  CustomizedSetter createCustomizedSetter();

  /**
   * Returns a new object of class '<em>Config</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Config</em>'.
   * @generated
   */
  Config createConfig();

  /**
   * Returns a new object of class '<em>Transformation Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Transformation Rule</em>'.
   * @generated
   */
  TransformationRule createTransformationRule();

  /**
   * Returns a new object of class '<em>Class Matcher</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Class Matcher</em>'.
   * @generated
   */
  ClassMatcher createClassMatcher();

  /**
   * Returns a new object of class '<em>Src Class Matcher</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Src Class Matcher</em>'.
   * @generated
   */
  SrcClassMatcher createSrcClassMatcher();

  /**
   * Returns a new object of class '<em>Trg Class Matcher</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Trg Class Matcher</em>'.
   * @generated
   */
  TrgClassMatcher createTrgClassMatcher();

  /**
   * Returns a new object of class '<em>Class Matcher Modifier</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Class Matcher Modifier</em>'.
   * @generated
   */
  ClassMatcherModifier createClassMatcherModifier();

  /**
   * Returns a new object of class '<em>Feature Mapping</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Feature Mapping</em>'.
   * @generated
   */
  FeatureMapping createFeatureMapping();

  /**
   * Returns a new object of class '<em>Mapping Feature</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mapping Feature</em>'.
   * @generated
   */
  MappingFeature createMappingFeature();

  /**
   * Returns a new object of class '<em>Src Mapping Feature</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Src Mapping Feature</em>'.
   * @generated
   */
  SrcMappingFeature createSrcMappingFeature();

  /**
   * Returns a new object of class '<em>Trg Mapping Feature</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Trg Mapping Feature</em>'.
   * @generated
   */
  TrgMappingFeature createTrgMappingFeature();

  /**
   * Returns a new object of class '<em>Correspondence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Correspondence</em>'.
   * @generated
   */
  Correspondence createCorrespondence();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  BXtendDSLPackage getBXtendDSLPackage();

} //BXtendDSLFactory
