/**
 * generated by Xtext 2.16.0
 */
package de.ubt.ai1.m2m.bxtenddsl.bXtendDSL;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EStructuralFeature;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Customized Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.CustomizedElement#getElement <em>Element</em>}</li>
 *   <li>{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.CustomizedElement#getCustomId <em>Custom Id</em>}</li>
 * </ul>
 *
 * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.BXtendDSLPackage#getCustomizedElement()
 * @model
 * @generated
 */
public interface CustomizedElement extends EObject
{
  /**
   * Returns the value of the '<em><b>Element</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Element</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element</em>' reference.
   * @see #setElement(EStructuralFeature)
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.BXtendDSLPackage#getCustomizedElement_Element()
   * @model
   * @generated
   */
  EStructuralFeature getElement();

  /**
   * Sets the value of the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.CustomizedElement#getElement <em>Element</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element</em>' reference.
   * @see #getElement()
   * @generated
   */
  void setElement(EStructuralFeature value);

  /**
   * Returns the value of the '<em><b>Custom Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Custom Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Custom Id</em>' attribute.
   * @see #setCustomId(String)
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.BXtendDSLPackage#getCustomizedElement_CustomId()
   * @model
   * @generated
   */
  String getCustomId();

  /**
   * Sets the value of the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.CustomizedElement#getCustomId <em>Custom Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Custom Id</em>' attribute.
   * @see #getCustomId()
   * @generated
   */
  void setCustomId(String value);

} // CustomizedElement
