/**
 * generated by Xtext 2.16.0
 */
package de.ubt.ai1.m2m.bxtenddsl.bXtendDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Customized Getter</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.BXtendDSLPackage#getCustomizedGetter()
 * @model
 * @generated
 */
public interface CustomizedGetter extends CustomizedElement
{
} // CustomizedGetter
