/**
 * generated by Xtext 2.16.0
 */
package de.ubt.ai1.m2m.bxtenddsl.bXtendDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transformation Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.TransformationRule#getName <em>Name</em>}</li>
 *   <li>{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.TransformationRule#getSrcMatcher <em>Src Matcher</em>}</li>
 *   <li>{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.TransformationRule#getTrgMatcher <em>Trg Matcher</em>}</li>
 *   <li>{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.TransformationRule#getMappings <em>Mappings</em>}</li>
 * </ul>
 *
 * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.BXtendDSLPackage#getTransformationRule()
 * @model
 * @generated
 */
public interface TransformationRule extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.BXtendDSLPackage#getTransformationRule_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.TransformationRule#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Src Matcher</b></em>' containment reference list.
   * The list contents are of type {@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.SrcClassMatcher}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Src Matcher</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Src Matcher</em>' containment reference list.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.BXtendDSLPackage#getTransformationRule_SrcMatcher()
   * @model containment="true"
   * @generated
   */
  EList<SrcClassMatcher> getSrcMatcher();

  /**
   * Returns the value of the '<em><b>Trg Matcher</b></em>' containment reference list.
   * The list contents are of type {@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.TrgClassMatcher}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Trg Matcher</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trg Matcher</em>' containment reference list.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.BXtendDSLPackage#getTransformationRule_TrgMatcher()
   * @model containment="true"
   * @generated
   */
  EList<TrgClassMatcher> getTrgMatcher();

  /**
   * Returns the value of the '<em><b>Mappings</b></em>' containment reference list.
   * The list contents are of type {@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.FeatureMapping}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mappings</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mappings</em>' containment reference list.
   * @see de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.BXtendDSLPackage#getTransformationRule_Mappings()
   * @model containment="true"
   * @generated
   */
  EList<FeatureMapping> getMappings();

} // TransformationRule
