/*
 * generated by Xtext 2.15.0
 */
package de.ubt.ai1.m2m.bxtenddsl.parser.antlr;

import de.ubt.ai1.m2m.bxtenddsl.parser.antlr.internal.InternalBXtendDSLParser;
import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;

public class BXtendDSLTokenSource extends AbstractIndentationTokenSource {
	public BXtendDSLTokenSource(TokenSource delegate) {
		super(delegate);
	}

	@Override
	protected boolean shouldSplitTokenImpl(Token token) {
		return token.getType() == InternalBXtendDSLParser.RULE_INDENTATION;
	}

	@Override
	protected int getBeginTokenType() {
		return InternalBXtendDSLParser.RULE_TAB_INDENTED_BLOCK_BEGIN;
	}

	@Override
	protected int getEndTokenType() {
		return InternalBXtendDSLParser.RULE_TAB_INDENTED_BLOCK_END;
	}
	
	@Override
	protected boolean shouldEmitPendingEndTokens() {
		return false;
	}
}
