/**
 * generated by Xtext 2.16.0
 */
package de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl;

import de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.BXtendDSLPackage;
import de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.ClassMatcherModifier;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Class Matcher Modifier</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.ClassMatcherModifierImpl#isFilter <em>Filter</em>}</li>
 *   <li>{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.ClassMatcherModifierImpl#isSort <em>Sort</em>}</li>
 *   <li>{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.ClassMatcherModifierImpl#isCreation <em>Creation</em>}</li>
 *   <li>{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.ClassMatcherModifierImpl#isDeletion <em>Deletion</em>}</li>
 *   <li>{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.ClassMatcherModifierImpl#isGroup <em>Group</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ClassMatcherModifierImpl extends MinimalEObjectImpl.Container implements ClassMatcherModifier
{
  /**
   * The default value of the '{@link #isFilter() <em>Filter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isFilter()
   * @generated
   * @ordered
   */
  protected static final boolean FILTER_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isFilter() <em>Filter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isFilter()
   * @generated
   * @ordered
   */
  protected boolean filter = FILTER_EDEFAULT;

  /**
   * The default value of the '{@link #isSort() <em>Sort</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isSort()
   * @generated
   * @ordered
   */
  protected static final boolean SORT_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isSort() <em>Sort</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isSort()
   * @generated
   * @ordered
   */
  protected boolean sort = SORT_EDEFAULT;

  /**
   * The default value of the '{@link #isCreation() <em>Creation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isCreation()
   * @generated
   * @ordered
   */
  protected static final boolean CREATION_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isCreation() <em>Creation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isCreation()
   * @generated
   * @ordered
   */
  protected boolean creation = CREATION_EDEFAULT;

  /**
   * The default value of the '{@link #isDeletion() <em>Deletion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isDeletion()
   * @generated
   * @ordered
   */
  protected static final boolean DELETION_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isDeletion() <em>Deletion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isDeletion()
   * @generated
   * @ordered
   */
  protected boolean deletion = DELETION_EDEFAULT;

  /**
   * The default value of the '{@link #isGroup() <em>Group</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isGroup()
   * @generated
   * @ordered
   */
  protected static final boolean GROUP_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isGroup() <em>Group</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isGroup()
   * @generated
   * @ordered
   */
  protected boolean group = GROUP_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ClassMatcherModifierImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BXtendDSLPackage.Literals.CLASS_MATCHER_MODIFIER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isFilter()
  {
    return filter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFilter(boolean newFilter)
  {
    boolean oldFilter = filter;
    filter = newFilter;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BXtendDSLPackage.CLASS_MATCHER_MODIFIER__FILTER, oldFilter, filter));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isSort()
  {
    return sort;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSort(boolean newSort)
  {
    boolean oldSort = sort;
    sort = newSort;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BXtendDSLPackage.CLASS_MATCHER_MODIFIER__SORT, oldSort, sort));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isCreation()
  {
    return creation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCreation(boolean newCreation)
  {
    boolean oldCreation = creation;
    creation = newCreation;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BXtendDSLPackage.CLASS_MATCHER_MODIFIER__CREATION, oldCreation, creation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isDeletion()
  {
    return deletion;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDeletion(boolean newDeletion)
  {
    boolean oldDeletion = deletion;
    deletion = newDeletion;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BXtendDSLPackage.CLASS_MATCHER_MODIFIER__DELETION, oldDeletion, deletion));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isGroup()
  {
    return group;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setGroup(boolean newGroup)
  {
    boolean oldGroup = group;
    group = newGroup;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BXtendDSLPackage.CLASS_MATCHER_MODIFIER__GROUP, oldGroup, group));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BXtendDSLPackage.CLASS_MATCHER_MODIFIER__FILTER:
        return isFilter();
      case BXtendDSLPackage.CLASS_MATCHER_MODIFIER__SORT:
        return isSort();
      case BXtendDSLPackage.CLASS_MATCHER_MODIFIER__CREATION:
        return isCreation();
      case BXtendDSLPackage.CLASS_MATCHER_MODIFIER__DELETION:
        return isDeletion();
      case BXtendDSLPackage.CLASS_MATCHER_MODIFIER__GROUP:
        return isGroup();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BXtendDSLPackage.CLASS_MATCHER_MODIFIER__FILTER:
        setFilter((Boolean)newValue);
        return;
      case BXtendDSLPackage.CLASS_MATCHER_MODIFIER__SORT:
        setSort((Boolean)newValue);
        return;
      case BXtendDSLPackage.CLASS_MATCHER_MODIFIER__CREATION:
        setCreation((Boolean)newValue);
        return;
      case BXtendDSLPackage.CLASS_MATCHER_MODIFIER__DELETION:
        setDeletion((Boolean)newValue);
        return;
      case BXtendDSLPackage.CLASS_MATCHER_MODIFIER__GROUP:
        setGroup((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BXtendDSLPackage.CLASS_MATCHER_MODIFIER__FILTER:
        setFilter(FILTER_EDEFAULT);
        return;
      case BXtendDSLPackage.CLASS_MATCHER_MODIFIER__SORT:
        setSort(SORT_EDEFAULT);
        return;
      case BXtendDSLPackage.CLASS_MATCHER_MODIFIER__CREATION:
        setCreation(CREATION_EDEFAULT);
        return;
      case BXtendDSLPackage.CLASS_MATCHER_MODIFIER__DELETION:
        setDeletion(DELETION_EDEFAULT);
        return;
      case BXtendDSLPackage.CLASS_MATCHER_MODIFIER__GROUP:
        setGroup(GROUP_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BXtendDSLPackage.CLASS_MATCHER_MODIFIER__FILTER:
        return filter != FILTER_EDEFAULT;
      case BXtendDSLPackage.CLASS_MATCHER_MODIFIER__SORT:
        return sort != SORT_EDEFAULT;
      case BXtendDSLPackage.CLASS_MATCHER_MODIFIER__CREATION:
        return creation != CREATION_EDEFAULT;
      case BXtendDSLPackage.CLASS_MATCHER_MODIFIER__DELETION:
        return deletion != DELETION_EDEFAULT;
      case BXtendDSLPackage.CLASS_MATCHER_MODIFIER__GROUP:
        return group != GROUP_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (filter: ");
    result.append(filter);
    result.append(", sort: ");
    result.append(sort);
    result.append(", creation: ");
    result.append(creation);
    result.append(", deletion: ");
    result.append(deletion);
    result.append(", group: ");
    result.append(group);
    result.append(')');
    return result.toString();
  }

} //ClassMatcherModifierImpl
