/**
 * generated by Xtext 2.16.0
 */
package de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl;

import de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.BXtendDSLPackage;
import de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.CustomizedElement;
import de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.Metamodels;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Metamodels</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.MetamodelsImpl#getSourcemodel <em>Sourcemodel</em>}</li>
 *   <li>{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.MetamodelsImpl#getCustomizedSrcElements <em>Customized Src Elements</em>}</li>
 *   <li>{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.MetamodelsImpl#getTargetmodel <em>Targetmodel</em>}</li>
 *   <li>{@link de.ubt.ai1.m2m.bxtenddsl.bXtendDSL.impl.MetamodelsImpl#getCustomizedTrgElements <em>Customized Trg Elements</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MetamodelsImpl extends MinimalEObjectImpl.Container implements Metamodels
{
  /**
   * The default value of the '{@link #getSourcemodel() <em>Sourcemodel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSourcemodel()
   * @generated
   * @ordered
   */
  protected static final String SOURCEMODEL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSourcemodel() <em>Sourcemodel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSourcemodel()
   * @generated
   * @ordered
   */
  protected String sourcemodel = SOURCEMODEL_EDEFAULT;

  /**
   * The cached value of the '{@link #getCustomizedSrcElements() <em>Customized Src Elements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCustomizedSrcElements()
   * @generated
   * @ordered
   */
  protected EList<CustomizedElement> customizedSrcElements;

  /**
   * The default value of the '{@link #getTargetmodel() <em>Targetmodel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTargetmodel()
   * @generated
   * @ordered
   */
  protected static final String TARGETMODEL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTargetmodel() <em>Targetmodel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTargetmodel()
   * @generated
   * @ordered
   */
  protected String targetmodel = TARGETMODEL_EDEFAULT;

  /**
   * The cached value of the '{@link #getCustomizedTrgElements() <em>Customized Trg Elements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCustomizedTrgElements()
   * @generated
   * @ordered
   */
  protected EList<CustomizedElement> customizedTrgElements;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MetamodelsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BXtendDSLPackage.Literals.METAMODELS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSourcemodel()
  {
    return sourcemodel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSourcemodel(String newSourcemodel)
  {
    String oldSourcemodel = sourcemodel;
    sourcemodel = newSourcemodel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BXtendDSLPackage.METAMODELS__SOURCEMODEL, oldSourcemodel, sourcemodel));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<CustomizedElement> getCustomizedSrcElements()
  {
    if (customizedSrcElements == null)
    {
      customizedSrcElements = new EObjectContainmentEList<CustomizedElement>(CustomizedElement.class, this, BXtendDSLPackage.METAMODELS__CUSTOMIZED_SRC_ELEMENTS);
    }
    return customizedSrcElements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTargetmodel()
  {
    return targetmodel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTargetmodel(String newTargetmodel)
  {
    String oldTargetmodel = targetmodel;
    targetmodel = newTargetmodel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BXtendDSLPackage.METAMODELS__TARGETMODEL, oldTargetmodel, targetmodel));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<CustomizedElement> getCustomizedTrgElements()
  {
    if (customizedTrgElements == null)
    {
      customizedTrgElements = new EObjectContainmentEList<CustomizedElement>(CustomizedElement.class, this, BXtendDSLPackage.METAMODELS__CUSTOMIZED_TRG_ELEMENTS);
    }
    return customizedTrgElements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case BXtendDSLPackage.METAMODELS__CUSTOMIZED_SRC_ELEMENTS:
        return ((InternalEList<?>)getCustomizedSrcElements()).basicRemove(otherEnd, msgs);
      case BXtendDSLPackage.METAMODELS__CUSTOMIZED_TRG_ELEMENTS:
        return ((InternalEList<?>)getCustomizedTrgElements()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BXtendDSLPackage.METAMODELS__SOURCEMODEL:
        return getSourcemodel();
      case BXtendDSLPackage.METAMODELS__CUSTOMIZED_SRC_ELEMENTS:
        return getCustomizedSrcElements();
      case BXtendDSLPackage.METAMODELS__TARGETMODEL:
        return getTargetmodel();
      case BXtendDSLPackage.METAMODELS__CUSTOMIZED_TRG_ELEMENTS:
        return getCustomizedTrgElements();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BXtendDSLPackage.METAMODELS__SOURCEMODEL:
        setSourcemodel((String)newValue);
        return;
      case BXtendDSLPackage.METAMODELS__CUSTOMIZED_SRC_ELEMENTS:
        getCustomizedSrcElements().clear();
        getCustomizedSrcElements().addAll((Collection<? extends CustomizedElement>)newValue);
        return;
      case BXtendDSLPackage.METAMODELS__TARGETMODEL:
        setTargetmodel((String)newValue);
        return;
      case BXtendDSLPackage.METAMODELS__CUSTOMIZED_TRG_ELEMENTS:
        getCustomizedTrgElements().clear();
        getCustomizedTrgElements().addAll((Collection<? extends CustomizedElement>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BXtendDSLPackage.METAMODELS__SOURCEMODEL:
        setSourcemodel(SOURCEMODEL_EDEFAULT);
        return;
      case BXtendDSLPackage.METAMODELS__CUSTOMIZED_SRC_ELEMENTS:
        getCustomizedSrcElements().clear();
        return;
      case BXtendDSLPackage.METAMODELS__TARGETMODEL:
        setTargetmodel(TARGETMODEL_EDEFAULT);
        return;
      case BXtendDSLPackage.METAMODELS__CUSTOMIZED_TRG_ELEMENTS:
        getCustomizedTrgElements().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BXtendDSLPackage.METAMODELS__SOURCEMODEL:
        return SOURCEMODEL_EDEFAULT == null ? sourcemodel != null : !SOURCEMODEL_EDEFAULT.equals(sourcemodel);
      case BXtendDSLPackage.METAMODELS__CUSTOMIZED_SRC_ELEMENTS:
        return customizedSrcElements != null && !customizedSrcElements.isEmpty();
      case BXtendDSLPackage.METAMODELS__TARGETMODEL:
        return TARGETMODEL_EDEFAULT == null ? targetmodel != null : !TARGETMODEL_EDEFAULT.equals(targetmodel);
      case BXtendDSLPackage.METAMODELS__CUSTOMIZED_TRG_ELEMENTS:
        return customizedTrgElements != null && !customizedTrgElements.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (sourcemodel: ");
    result.append(sourcemodel);
    result.append(", targetmodel: ");
    result.append(targetmodel);
    result.append(')');
    return result.toString();
  }

} //MetamodelsImpl
