/**
 * generated by Xtext 2.15.0
 */
package de.ubt.ai1.m2m.bxtenddsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.ubt.ai1.m2m.bxtenddsl.BXtendDSLRuntimeModule;
import de.ubt.ai1.m2m.bxtenddsl.BXtendDSLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class BXtendDSLIdeSetup extends BXtendDSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    BXtendDSLRuntimeModule _bXtendDSLRuntimeModule = new BXtendDSLRuntimeModule();
    BXtendDSLIdeModule _bXtendDSLIdeModule = new BXtendDSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_bXtendDSLRuntimeModule, _bXtendDSLIdeModule));
  }
}
