/**
 * generated by Xtext 2.15.0
 */
package de.ubt.ai1.m2m.bxtenddsl.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class BXtendDSLIdeModule extends AbstractBXtendDSLIdeModule {
}
