/*
 * generated by Xtext 2.16.0
 */
package de.ubt.ai1.m2m.bxtenddsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.UnorderedGroup;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class BXtendDSLGrammarAccess extends AbstractGrammarElementFinder {
	
	public class BXtendDSLElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.ubt.ai1.m2m.bxtenddsl.BXtendDSL.BXtendDSL");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cMetamodelsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cMetamodelsMetamodelsParserRuleCall_0_0 = (RuleCall)cMetamodelsAssignment_0.eContents().get(0);
		private final Assignment cConfigAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cConfigConfigParserRuleCall_1_0 = (RuleCall)cConfigAssignment_1.eContents().get(0);
		private final Assignment cRulesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cRulesTransformationRuleParserRuleCall_2_0 = (RuleCall)cRulesAssignment_2.eContents().get(0);
		
		//BXtendDSL:
		//	metamodels=Metamodels
		//	config=Config
		//	rules+=TransformationRule*;
		@Override public ParserRule getRule() { return rule; }
		
		//metamodels=Metamodels config=Config rules+=TransformationRule*
		public Group getGroup() { return cGroup; }
		
		//metamodels=Metamodels
		public Assignment getMetamodelsAssignment_0() { return cMetamodelsAssignment_0; }
		
		//Metamodels
		public RuleCall getMetamodelsMetamodelsParserRuleCall_0_0() { return cMetamodelsMetamodelsParserRuleCall_0_0; }
		
		//config=Config
		public Assignment getConfigAssignment_1() { return cConfigAssignment_1; }
		
		//Config
		public RuleCall getConfigConfigParserRuleCall_1_0() { return cConfigConfigParserRuleCall_1_0; }
		
		//rules+=TransformationRule*
		public Assignment getRulesAssignment_2() { return cRulesAssignment_2; }
		
		//TransformationRule
		public RuleCall getRulesTransformationRuleParserRuleCall_2_0() { return cRulesTransformationRuleParserRuleCall_2_0; }
	}
	public class MetamodelsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.ubt.ai1.m2m.bxtenddsl.BXtendDSL.Metamodels");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSourcemodelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cSourcemodelAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cSourcemodelSTRINGTerminalRuleCall_1_0 = (RuleCall)cSourcemodelAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final RuleCall cTAB_INDENTED_BLOCK_BEGINTerminalRuleCall_2_0 = (RuleCall)cGroup_2.eContents().get(0);
		private final Assignment cCustomizedSrcElementsAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cCustomizedSrcElementsCustomizedElementParserRuleCall_2_1_0 = (RuleCall)cCustomizedSrcElementsAssignment_2_1.eContents().get(0);
		private final RuleCall cTAB_INDENTED_BLOCK_ENDTerminalRuleCall_2_2 = (RuleCall)cGroup_2.eContents().get(2);
		private final Keyword cTargetmodelKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTargetmodelAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTargetmodelSTRINGTerminalRuleCall_4_0 = (RuleCall)cTargetmodelAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final RuleCall cTAB_INDENTED_BLOCK_BEGINTerminalRuleCall_5_0 = (RuleCall)cGroup_5.eContents().get(0);
		private final Assignment cCustomizedTrgElementsAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cCustomizedTrgElementsCustomizedElementParserRuleCall_5_1_0 = (RuleCall)cCustomizedTrgElementsAssignment_5_1.eContents().get(0);
		private final RuleCall cTAB_INDENTED_BLOCK_ENDTerminalRuleCall_5_2 = (RuleCall)cGroup_5.eContents().get(2);
		
		//Metamodels:
		//	'sourcemodel' sourcemodel=STRING (TAB_INDENTED_BLOCK_BEGIN
		//	customizedSrcElements+=CustomizedElement+
		//	TAB_INDENTED_BLOCK_END)?
		//	'targetmodel' targetmodel=STRING (TAB_INDENTED_BLOCK_BEGIN
		//	customizedTrgElements+=CustomizedElement+
		//	TAB_INDENTED_BLOCK_END)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'sourcemodel' sourcemodel=STRING (TAB_INDENTED_BLOCK_BEGIN customizedSrcElements+=CustomizedElement+
		//TAB_INDENTED_BLOCK_END)? 'targetmodel' targetmodel=STRING (TAB_INDENTED_BLOCK_BEGIN
		//customizedTrgElements+=CustomizedElement+ TAB_INDENTED_BLOCK_END)?
		public Group getGroup() { return cGroup; }
		
		//'sourcemodel'
		public Keyword getSourcemodelKeyword_0() { return cSourcemodelKeyword_0; }
		
		//sourcemodel=STRING
		public Assignment getSourcemodelAssignment_1() { return cSourcemodelAssignment_1; }
		
		//STRING
		public RuleCall getSourcemodelSTRINGTerminalRuleCall_1_0() { return cSourcemodelSTRINGTerminalRuleCall_1_0; }
		
		//(TAB_INDENTED_BLOCK_BEGIN customizedSrcElements+=CustomizedElement+ TAB_INDENTED_BLOCK_END)?
		public Group getGroup_2() { return cGroup_2; }
		
		//TAB_INDENTED_BLOCK_BEGIN
		public RuleCall getTAB_INDENTED_BLOCK_BEGINTerminalRuleCall_2_0() { return cTAB_INDENTED_BLOCK_BEGINTerminalRuleCall_2_0; }
		
		//customizedSrcElements+=CustomizedElement+
		public Assignment getCustomizedSrcElementsAssignment_2_1() { return cCustomizedSrcElementsAssignment_2_1; }
		
		//CustomizedElement
		public RuleCall getCustomizedSrcElementsCustomizedElementParserRuleCall_2_1_0() { return cCustomizedSrcElementsCustomizedElementParserRuleCall_2_1_0; }
		
		//TAB_INDENTED_BLOCK_END
		public RuleCall getTAB_INDENTED_BLOCK_ENDTerminalRuleCall_2_2() { return cTAB_INDENTED_BLOCK_ENDTerminalRuleCall_2_2; }
		
		//'targetmodel'
		public Keyword getTargetmodelKeyword_3() { return cTargetmodelKeyword_3; }
		
		//targetmodel=STRING
		public Assignment getTargetmodelAssignment_4() { return cTargetmodelAssignment_4; }
		
		//STRING
		public RuleCall getTargetmodelSTRINGTerminalRuleCall_4_0() { return cTargetmodelSTRINGTerminalRuleCall_4_0; }
		
		//(TAB_INDENTED_BLOCK_BEGIN customizedTrgElements+=CustomizedElement+ TAB_INDENTED_BLOCK_END)?
		public Group getGroup_5() { return cGroup_5; }
		
		//TAB_INDENTED_BLOCK_BEGIN
		public RuleCall getTAB_INDENTED_BLOCK_BEGINTerminalRuleCall_5_0() { return cTAB_INDENTED_BLOCK_BEGINTerminalRuleCall_5_0; }
		
		//customizedTrgElements+=CustomizedElement+
		public Assignment getCustomizedTrgElementsAssignment_5_1() { return cCustomizedTrgElementsAssignment_5_1; }
		
		//CustomizedElement
		public RuleCall getCustomizedTrgElementsCustomizedElementParserRuleCall_5_1_0() { return cCustomizedTrgElementsCustomizedElementParserRuleCall_5_1_0; }
		
		//TAB_INDENTED_BLOCK_END
		public RuleCall getTAB_INDENTED_BLOCK_ENDTerminalRuleCall_5_2() { return cTAB_INDENTED_BLOCK_ENDTerminalRuleCall_5_2; }
	}
	public class CustomizedElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.ubt.ai1.m2m.bxtenddsl.BXtendDSL.CustomizedElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCustomizedGetterParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cCustomizedSetterParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//CustomizedElement:
		//	CustomizedGetter | CustomizedSetter;
		@Override public ParserRule getRule() { return rule; }
		
		//CustomizedGetter | CustomizedSetter
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//CustomizedGetter
		public RuleCall getCustomizedGetterParserRuleCall_0() { return cCustomizedGetterParserRuleCall_0; }
		
		//CustomizedSetter
		public RuleCall getCustomizedSetterParserRuleCall_1() { return cCustomizedSetterParserRuleCall_1; }
	}
	public class CustomizedGetterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.ubt.ai1.m2m.bxtenddsl.BXtendDSL.CustomizedGetter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGetKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cElementAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cElementEStructuralFeatureCrossReference_1_0 = (CrossReference)cElementAssignment_1.eContents().get(0);
		private final RuleCall cElementEStructuralFeatureFeatureAccessParserRuleCall_1_0_1 = (RuleCall)cElementEStructuralFeatureCrossReference_1_0.eContents().get(1);
		private final Keyword cAsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cCustomIdAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cCustomIdIDTerminalRuleCall_3_0 = (RuleCall)cCustomIdAssignment_3.eContents().get(0);
		
		//CustomizedGetter:
		//	'get' element=[EStructuralFeature|FeatureAccess] 'as' customId=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//'get' element=[EStructuralFeature|FeatureAccess] 'as' customId=ID
		public Group getGroup() { return cGroup; }
		
		//'get'
		public Keyword getGetKeyword_0() { return cGetKeyword_0; }
		
		//element=[EStructuralFeature|FeatureAccess]
		public Assignment getElementAssignment_1() { return cElementAssignment_1; }
		
		//[EStructuralFeature|FeatureAccess]
		public CrossReference getElementEStructuralFeatureCrossReference_1_0() { return cElementEStructuralFeatureCrossReference_1_0; }
		
		//FeatureAccess
		public RuleCall getElementEStructuralFeatureFeatureAccessParserRuleCall_1_0_1() { return cElementEStructuralFeatureFeatureAccessParserRuleCall_1_0_1; }
		
		//'as'
		public Keyword getAsKeyword_2() { return cAsKeyword_2; }
		
		//customId=ID
		public Assignment getCustomIdAssignment_3() { return cCustomIdAssignment_3; }
		
		//ID
		public RuleCall getCustomIdIDTerminalRuleCall_3_0() { return cCustomIdIDTerminalRuleCall_3_0; }
	}
	public class CustomizedSetterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.ubt.ai1.m2m.bxtenddsl.BXtendDSL.CustomizedSetter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSetKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cElementAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cElementEStructuralFeatureCrossReference_1_0 = (CrossReference)cElementAssignment_1.eContents().get(0);
		private final RuleCall cElementEStructuralFeatureFeatureAccessParserRuleCall_1_0_1 = (RuleCall)cElementEStructuralFeatureCrossReference_1_0.eContents().get(1);
		private final Keyword cAsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cCustomIdAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cCustomIdIDTerminalRuleCall_3_0 = (RuleCall)cCustomIdAssignment_3.eContents().get(0);
		
		//CustomizedSetter:
		//	'set' element=[EStructuralFeature|FeatureAccess] 'as' customId=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//'set' element=[EStructuralFeature|FeatureAccess] 'as' customId=ID
		public Group getGroup() { return cGroup; }
		
		//'set'
		public Keyword getSetKeyword_0() { return cSetKeyword_0; }
		
		//element=[EStructuralFeature|FeatureAccess]
		public Assignment getElementAssignment_1() { return cElementAssignment_1; }
		
		//[EStructuralFeature|FeatureAccess]
		public CrossReference getElementEStructuralFeatureCrossReference_1_0() { return cElementEStructuralFeatureCrossReference_1_0; }
		
		//FeatureAccess
		public RuleCall getElementEStructuralFeatureFeatureAccessParserRuleCall_1_0_1() { return cElementEStructuralFeatureFeatureAccessParserRuleCall_1_0_1; }
		
		//'as'
		public Keyword getAsKeyword_2() { return cAsKeyword_2; }
		
		//customId=ID
		public Assignment getCustomIdAssignment_3() { return cCustomIdAssignment_3; }
		
		//ID
		public RuleCall getCustomIdIDTerminalRuleCall_3_0() { return cCustomIdIDTerminalRuleCall_3_0; }
	}
	public class ConfigElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.ubt.ai1.m2m.bxtenddsl.BXtendDSL.Config");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cConfigAction_0 = (Action)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cOptionsKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cTAB_INDENTED_BLOCK_BEGINTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Assignment cOptionsAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cOptionsIDTerminalRuleCall_1_2_0 = (RuleCall)cOptionsAssignment_1_2.eContents().get(0);
		private final RuleCall cTAB_INDENTED_BLOCK_ENDTerminalRuleCall_1_3 = (RuleCall)cGroup_1.eContents().get(3);
		
		//Config:
		//	{Config} ('options'
		//	TAB_INDENTED_BLOCK_BEGIN
		//	options+=ID+
		//	TAB_INDENTED_BLOCK_END)?;
		@Override public ParserRule getRule() { return rule; }
		
		//{Config} ('options' TAB_INDENTED_BLOCK_BEGIN options+=ID+ TAB_INDENTED_BLOCK_END)?
		public Group getGroup() { return cGroup; }
		
		//{Config}
		public Action getConfigAction_0() { return cConfigAction_0; }
		
		//('options' TAB_INDENTED_BLOCK_BEGIN options+=ID+ TAB_INDENTED_BLOCK_END)?
		public Group getGroup_1() { return cGroup_1; }
		
		//'options'
		public Keyword getOptionsKeyword_1_0() { return cOptionsKeyword_1_0; }
		
		//TAB_INDENTED_BLOCK_BEGIN
		public RuleCall getTAB_INDENTED_BLOCK_BEGINTerminalRuleCall_1_1() { return cTAB_INDENTED_BLOCK_BEGINTerminalRuleCall_1_1; }
		
		//options+=ID+
		public Assignment getOptionsAssignment_1_2() { return cOptionsAssignment_1_2; }
		
		//ID
		public RuleCall getOptionsIDTerminalRuleCall_1_2_0() { return cOptionsIDTerminalRuleCall_1_2_0; }
		
		//TAB_INDENTED_BLOCK_END
		public RuleCall getTAB_INDENTED_BLOCK_ENDTerminalRuleCall_1_3() { return cTAB_INDENTED_BLOCK_ENDTerminalRuleCall_1_3; }
	}
	public class TransformationRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.ubt.ai1.m2m.bxtenddsl.BXtendDSL.TransformationRule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRuleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final RuleCall cTAB_INDENTED_BLOCK_BEGINTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Keyword cSrcKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cSrcMatcherAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cSrcMatcherSrcClassMatcherParserRuleCall_4_0 = (RuleCall)cSrcMatcherAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final RuleCall cTAB_INDENTED_BLOCK_BEGINTerminalRuleCall_5_0 = (RuleCall)cGroup_5.eContents().get(0);
		private final Assignment cSrcMatcherAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cSrcMatcherSrcClassMatcherParserRuleCall_5_1_0 = (RuleCall)cSrcMatcherAssignment_5_1.eContents().get(0);
		private final RuleCall cTAB_INDENTED_BLOCK_ENDTerminalRuleCall_5_2 = (RuleCall)cGroup_5.eContents().get(2);
		private final Keyword cTrgKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cTrgMatcherAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cTrgMatcherTrgClassMatcherParserRuleCall_7_0 = (RuleCall)cTrgMatcherAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final RuleCall cTAB_INDENTED_BLOCK_BEGINTerminalRuleCall_8_0 = (RuleCall)cGroup_8.eContents().get(0);
		private final Assignment cTrgMatcherAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cTrgMatcherTrgClassMatcherParserRuleCall_8_1_0 = (RuleCall)cTrgMatcherAssignment_8_1.eContents().get(0);
		private final RuleCall cTAB_INDENTED_BLOCK_ENDTerminalRuleCall_8_2 = (RuleCall)cGroup_8.eContents().get(2);
		private final Assignment cMappingsAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cMappingsFeatureMappingParserRuleCall_9_0 = (RuleCall)cMappingsAssignment_9.eContents().get(0);
		private final RuleCall cTAB_INDENTED_BLOCK_ENDTerminalRuleCall_10 = (RuleCall)cGroup.eContents().get(10);
		
		//TransformationRule:
		//	'rule' name=ID
		//	TAB_INDENTED_BLOCK_BEGIN
		//	'src' srcMatcher+=SrcClassMatcher (TAB_INDENTED_BLOCK_BEGIN
		//	srcMatcher+=SrcClassMatcher+
		//	TAB_INDENTED_BLOCK_END)?
		//	'trg' trgMatcher+=TrgClassMatcher (TAB_INDENTED_BLOCK_BEGIN
		//	trgMatcher+=TrgClassMatcher+
		//	TAB_INDENTED_BLOCK_END)?
		//	mappings+=FeatureMapping*
		//	TAB_INDENTED_BLOCK_END;
		@Override public ParserRule getRule() { return rule; }
		
		//'rule' name=ID TAB_INDENTED_BLOCK_BEGIN 'src' srcMatcher+=SrcClassMatcher (TAB_INDENTED_BLOCK_BEGIN
		//srcMatcher+=SrcClassMatcher+ TAB_INDENTED_BLOCK_END)? 'trg' trgMatcher+=TrgClassMatcher (TAB_INDENTED_BLOCK_BEGIN
		//trgMatcher+=TrgClassMatcher+ TAB_INDENTED_BLOCK_END)? mappings+=FeatureMapping* TAB_INDENTED_BLOCK_END
		public Group getGroup() { return cGroup; }
		
		//'rule'
		public Keyword getRuleKeyword_0() { return cRuleKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//TAB_INDENTED_BLOCK_BEGIN
		public RuleCall getTAB_INDENTED_BLOCK_BEGINTerminalRuleCall_2() { return cTAB_INDENTED_BLOCK_BEGINTerminalRuleCall_2; }
		
		//'src'
		public Keyword getSrcKeyword_3() { return cSrcKeyword_3; }
		
		//srcMatcher+=SrcClassMatcher
		public Assignment getSrcMatcherAssignment_4() { return cSrcMatcherAssignment_4; }
		
		//SrcClassMatcher
		public RuleCall getSrcMatcherSrcClassMatcherParserRuleCall_4_0() { return cSrcMatcherSrcClassMatcherParserRuleCall_4_0; }
		
		//(TAB_INDENTED_BLOCK_BEGIN srcMatcher+=SrcClassMatcher+ TAB_INDENTED_BLOCK_END)?
		public Group getGroup_5() { return cGroup_5; }
		
		//TAB_INDENTED_BLOCK_BEGIN
		public RuleCall getTAB_INDENTED_BLOCK_BEGINTerminalRuleCall_5_0() { return cTAB_INDENTED_BLOCK_BEGINTerminalRuleCall_5_0; }
		
		//srcMatcher+=SrcClassMatcher+
		public Assignment getSrcMatcherAssignment_5_1() { return cSrcMatcherAssignment_5_1; }
		
		//SrcClassMatcher
		public RuleCall getSrcMatcherSrcClassMatcherParserRuleCall_5_1_0() { return cSrcMatcherSrcClassMatcherParserRuleCall_5_1_0; }
		
		//TAB_INDENTED_BLOCK_END
		public RuleCall getTAB_INDENTED_BLOCK_ENDTerminalRuleCall_5_2() { return cTAB_INDENTED_BLOCK_ENDTerminalRuleCall_5_2; }
		
		//'trg'
		public Keyword getTrgKeyword_6() { return cTrgKeyword_6; }
		
		//trgMatcher+=TrgClassMatcher
		public Assignment getTrgMatcherAssignment_7() { return cTrgMatcherAssignment_7; }
		
		//TrgClassMatcher
		public RuleCall getTrgMatcherTrgClassMatcherParserRuleCall_7_0() { return cTrgMatcherTrgClassMatcherParserRuleCall_7_0; }
		
		//(TAB_INDENTED_BLOCK_BEGIN trgMatcher+=TrgClassMatcher+ TAB_INDENTED_BLOCK_END)?
		public Group getGroup_8() { return cGroup_8; }
		
		//TAB_INDENTED_BLOCK_BEGIN
		public RuleCall getTAB_INDENTED_BLOCK_BEGINTerminalRuleCall_8_0() { return cTAB_INDENTED_BLOCK_BEGINTerminalRuleCall_8_0; }
		
		//trgMatcher+=TrgClassMatcher+
		public Assignment getTrgMatcherAssignment_8_1() { return cTrgMatcherAssignment_8_1; }
		
		//TrgClassMatcher
		public RuleCall getTrgMatcherTrgClassMatcherParserRuleCall_8_1_0() { return cTrgMatcherTrgClassMatcherParserRuleCall_8_1_0; }
		
		//TAB_INDENTED_BLOCK_END
		public RuleCall getTAB_INDENTED_BLOCK_ENDTerminalRuleCall_8_2() { return cTAB_INDENTED_BLOCK_ENDTerminalRuleCall_8_2; }
		
		//mappings+=FeatureMapping*
		public Assignment getMappingsAssignment_9() { return cMappingsAssignment_9; }
		
		//FeatureMapping
		public RuleCall getMappingsFeatureMappingParserRuleCall_9_0() { return cMappingsFeatureMappingParserRuleCall_9_0; }
		
		//TAB_INDENTED_BLOCK_END
		public RuleCall getTAB_INDENTED_BLOCK_ENDTerminalRuleCall_10() { return cTAB_INDENTED_BLOCK_ENDTerminalRuleCall_10; }
	}
	public class ClassMatcherElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.ubt.ai1.m2m.bxtenddsl.BXtendDSL.ClassMatcher");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSrcClassMatcherParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTrgClassMatcherParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//ClassMatcher:
		//	SrcClassMatcher | TrgClassMatcher;
		@Override public ParserRule getRule() { return rule; }
		
		//SrcClassMatcher | TrgClassMatcher
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//SrcClassMatcher
		public RuleCall getSrcClassMatcherParserRuleCall_0() { return cSrcClassMatcherParserRuleCall_0; }
		
		//TrgClassMatcher
		public RuleCall getTrgClassMatcherParserRuleCall_1() { return cTrgClassMatcherParserRuleCall_1; }
	}
	public class SrcClassMatcherElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.ubt.ai1.m2m.bxtenddsl.BXtendDSL.SrcClassMatcher");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cClazzAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cClazzEClassCrossReference_0_0 = (CrossReference)cClazzAssignment_0.eContents().get(0);
		private final RuleCall cClazzEClassIDTerminalRuleCall_0_0_1 = (RuleCall)cClazzEClassCrossReference_0_0.eContents().get(1);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cModifierAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cModifierClassMatcherModifierParserRuleCall_2_0 = (RuleCall)cModifierAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//SrcClassMatcher:
		//	clazz=[EClass] name=ID modifier=ClassMatcherModifier ';';
		@Override public ParserRule getRule() { return rule; }
		
		//clazz=[EClass] name=ID modifier=ClassMatcherModifier ';'
		public Group getGroup() { return cGroup; }
		
		//clazz=[EClass]
		public Assignment getClazzAssignment_0() { return cClazzAssignment_0; }
		
		//[EClass]
		public CrossReference getClazzEClassCrossReference_0_0() { return cClazzEClassCrossReference_0_0; }
		
		//ID
		public RuleCall getClazzEClassIDTerminalRuleCall_0_0_1() { return cClazzEClassIDTerminalRuleCall_0_0_1; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//modifier=ClassMatcherModifier
		public Assignment getModifierAssignment_2() { return cModifierAssignment_2; }
		
		//ClassMatcherModifier
		public RuleCall getModifierClassMatcherModifierParserRuleCall_2_0() { return cModifierClassMatcherModifierParserRuleCall_2_0; }
		
		//';'
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}
	public class TrgClassMatcherElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.ubt.ai1.m2m.bxtenddsl.BXtendDSL.TrgClassMatcher");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cClazzAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cClazzEClassCrossReference_0_0 = (CrossReference)cClazzAssignment_0.eContents().get(0);
		private final RuleCall cClazzEClassIDTerminalRuleCall_0_0_1 = (RuleCall)cClazzEClassCrossReference_0_0.eContents().get(1);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cModifierAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cModifierClassMatcherModifierParserRuleCall_2_0 = (RuleCall)cModifierAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//TrgClassMatcher:
		//	clazz=[EClass] name=ID modifier=ClassMatcherModifier ';';
		@Override public ParserRule getRule() { return rule; }
		
		//clazz=[EClass] name=ID modifier=ClassMatcherModifier ';'
		public Group getGroup() { return cGroup; }
		
		//clazz=[EClass]
		public Assignment getClazzAssignment_0() { return cClazzAssignment_0; }
		
		//[EClass]
		public CrossReference getClazzEClassCrossReference_0_0() { return cClazzEClassCrossReference_0_0; }
		
		//ID
		public RuleCall getClazzEClassIDTerminalRuleCall_0_0_1() { return cClazzEClassIDTerminalRuleCall_0_0_1; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//modifier=ClassMatcherModifier
		public Assignment getModifierAssignment_2() { return cModifierAssignment_2; }
		
		//ClassMatcherModifier
		public RuleCall getModifierClassMatcherModifierParserRuleCall_2_0() { return cModifierClassMatcherModifierParserRuleCall_2_0; }
		
		//';'
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}
	public class ClassMatcherModifierElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.ubt.ai1.m2m.bxtenddsl.BXtendDSL.ClassMatcherModifier");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cClassMatcherModifierAction_0 = (Action)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Keyword cVerticalLineKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1_0_1 = (UnorderedGroup)cGroup_1_0.eContents().get(1);
		private final Group cGroup_1_0_1_0 = (Group)cUnorderedGroup_1_0_1.eContents().get(0);
		private final Assignment cFilterAssignment_1_0_1_0_0 = (Assignment)cGroup_1_0_1_0.eContents().get(0);
		private final Keyword cFilterFilterKeyword_1_0_1_0_0_0 = (Keyword)cFilterAssignment_1_0_1_0_0.eContents().get(0);
		private final Keyword cCommaKeyword_1_0_1_0_1 = (Keyword)cGroup_1_0_1_0.eContents().get(1);
		private final Group cGroup_1_0_1_1 = (Group)cUnorderedGroup_1_0_1.eContents().get(1);
		private final Assignment cSortAssignment_1_0_1_1_0 = (Assignment)cGroup_1_0_1_1.eContents().get(0);
		private final Keyword cSortSortKeyword_1_0_1_1_0_0 = (Keyword)cSortAssignment_1_0_1_1_0.eContents().get(0);
		private final Keyword cCommaKeyword_1_0_1_1_1 = (Keyword)cGroup_1_0_1_1.eContents().get(1);
		private final Group cGroup_1_0_1_2 = (Group)cUnorderedGroup_1_0_1.eContents().get(2);
		private final Assignment cCreationAssignment_1_0_1_2_0 = (Assignment)cGroup_1_0_1_2.eContents().get(0);
		private final Keyword cCreationCreationKeyword_1_0_1_2_0_0 = (Keyword)cCreationAssignment_1_0_1_2_0.eContents().get(0);
		private final Keyword cCommaKeyword_1_0_1_2_1 = (Keyword)cGroup_1_0_1_2.eContents().get(1);
		private final Group cGroup_1_0_1_3 = (Group)cUnorderedGroup_1_0_1.eContents().get(3);
		private final Assignment cDeletionAssignment_1_0_1_3_0 = (Assignment)cGroup_1_0_1_3.eContents().get(0);
		private final Keyword cDeletionDeletionKeyword_1_0_1_3_0_0 = (Keyword)cDeletionAssignment_1_0_1_3_0.eContents().get(0);
		private final Keyword cCommaKeyword_1_0_1_3_1 = (Keyword)cGroup_1_0_1_3.eContents().get(1);
		private final Assignment cGroupAssignment_1_0_2 = (Assignment)cGroup_1_0.eContents().get(2);
		private final Keyword cGroupGroupKeyword_1_0_2_0 = (Keyword)cGroupAssignment_1_0_2.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Keyword cVerticalLineKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1_1_1 = (UnorderedGroup)cGroup_1_1.eContents().get(1);
		private final Group cGroup_1_1_1_0 = (Group)cUnorderedGroup_1_1_1.eContents().get(0);
		private final Assignment cGroupAssignment_1_1_1_0_0 = (Assignment)cGroup_1_1_1_0.eContents().get(0);
		private final Keyword cGroupGroupKeyword_1_1_1_0_0_0 = (Keyword)cGroupAssignment_1_1_1_0_0.eContents().get(0);
		private final Keyword cCommaKeyword_1_1_1_0_1 = (Keyword)cGroup_1_1_1_0.eContents().get(1);
		private final Group cGroup_1_1_1_1 = (Group)cUnorderedGroup_1_1_1.eContents().get(1);
		private final Assignment cSortAssignment_1_1_1_1_0 = (Assignment)cGroup_1_1_1_1.eContents().get(0);
		private final Keyword cSortSortKeyword_1_1_1_1_0_0 = (Keyword)cSortAssignment_1_1_1_1_0.eContents().get(0);
		private final Keyword cCommaKeyword_1_1_1_1_1 = (Keyword)cGroup_1_1_1_1.eContents().get(1);
		private final Group cGroup_1_1_1_2 = (Group)cUnorderedGroup_1_1_1.eContents().get(2);
		private final Assignment cCreationAssignment_1_1_1_2_0 = (Assignment)cGroup_1_1_1_2.eContents().get(0);
		private final Keyword cCreationCreationKeyword_1_1_1_2_0_0 = (Keyword)cCreationAssignment_1_1_1_2_0.eContents().get(0);
		private final Keyword cCommaKeyword_1_1_1_2_1 = (Keyword)cGroup_1_1_1_2.eContents().get(1);
		private final Group cGroup_1_1_1_3 = (Group)cUnorderedGroup_1_1_1.eContents().get(3);
		private final Assignment cDeletionAssignment_1_1_1_3_0 = (Assignment)cGroup_1_1_1_3.eContents().get(0);
		private final Keyword cDeletionDeletionKeyword_1_1_1_3_0_0 = (Keyword)cDeletionAssignment_1_1_1_3_0.eContents().get(0);
		private final Keyword cCommaKeyword_1_1_1_3_1 = (Keyword)cGroup_1_1_1_3.eContents().get(1);
		private final Assignment cFilterAssignment_1_1_2 = (Assignment)cGroup_1_1.eContents().get(2);
		private final Keyword cFilterFilterKeyword_1_1_2_0 = (Keyword)cFilterAssignment_1_1_2.eContents().get(0);
		private final Group cGroup_1_2 = (Group)cAlternatives_1.eContents().get(2);
		private final Keyword cVerticalLineKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1_2_1 = (UnorderedGroup)cGroup_1_2.eContents().get(1);
		private final Group cGroup_1_2_1_0 = (Group)cUnorderedGroup_1_2_1.eContents().get(0);
		private final Assignment cGroupAssignment_1_2_1_0_0 = (Assignment)cGroup_1_2_1_0.eContents().get(0);
		private final Keyword cGroupGroupKeyword_1_2_1_0_0_0 = (Keyword)cGroupAssignment_1_2_1_0_0.eContents().get(0);
		private final Keyword cCommaKeyword_1_2_1_0_1 = (Keyword)cGroup_1_2_1_0.eContents().get(1);
		private final Group cGroup_1_2_1_1 = (Group)cUnorderedGroup_1_2_1.eContents().get(1);
		private final Assignment cFilterAssignment_1_2_1_1_0 = (Assignment)cGroup_1_2_1_1.eContents().get(0);
		private final Keyword cFilterFilterKeyword_1_2_1_1_0_0 = (Keyword)cFilterAssignment_1_2_1_1_0.eContents().get(0);
		private final Keyword cCommaKeyword_1_2_1_1_1 = (Keyword)cGroup_1_2_1_1.eContents().get(1);
		private final Group cGroup_1_2_1_2 = (Group)cUnorderedGroup_1_2_1.eContents().get(2);
		private final Assignment cCreationAssignment_1_2_1_2_0 = (Assignment)cGroup_1_2_1_2.eContents().get(0);
		private final Keyword cCreationCreationKeyword_1_2_1_2_0_0 = (Keyword)cCreationAssignment_1_2_1_2_0.eContents().get(0);
		private final Keyword cCommaKeyword_1_2_1_2_1 = (Keyword)cGroup_1_2_1_2.eContents().get(1);
		private final Group cGroup_1_2_1_3 = (Group)cUnorderedGroup_1_2_1.eContents().get(3);
		private final Assignment cDeletionAssignment_1_2_1_3_0 = (Assignment)cGroup_1_2_1_3.eContents().get(0);
		private final Keyword cDeletionDeletionKeyword_1_2_1_3_0_0 = (Keyword)cDeletionAssignment_1_2_1_3_0.eContents().get(0);
		private final Keyword cCommaKeyword_1_2_1_3_1 = (Keyword)cGroup_1_2_1_3.eContents().get(1);
		private final Assignment cSortAssignment_1_2_2 = (Assignment)cGroup_1_2.eContents().get(2);
		private final Keyword cSortSortKeyword_1_2_2_0 = (Keyword)cSortAssignment_1_2_2.eContents().get(0);
		private final Group cGroup_1_3 = (Group)cAlternatives_1.eContents().get(3);
		private final Keyword cVerticalLineKeyword_1_3_0 = (Keyword)cGroup_1_3.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1_3_1 = (UnorderedGroup)cGroup_1_3.eContents().get(1);
		private final Group cGroup_1_3_1_0 = (Group)cUnorderedGroup_1_3_1.eContents().get(0);
		private final Assignment cGroupAssignment_1_3_1_0_0 = (Assignment)cGroup_1_3_1_0.eContents().get(0);
		private final Keyword cGroupGroupKeyword_1_3_1_0_0_0 = (Keyword)cGroupAssignment_1_3_1_0_0.eContents().get(0);
		private final Keyword cCommaKeyword_1_3_1_0_1 = (Keyword)cGroup_1_3_1_0.eContents().get(1);
		private final Group cGroup_1_3_1_1 = (Group)cUnorderedGroup_1_3_1.eContents().get(1);
		private final Assignment cFilterAssignment_1_3_1_1_0 = (Assignment)cGroup_1_3_1_1.eContents().get(0);
		private final Keyword cFilterFilterKeyword_1_3_1_1_0_0 = (Keyword)cFilterAssignment_1_3_1_1_0.eContents().get(0);
		private final Keyword cCommaKeyword_1_3_1_1_1 = (Keyword)cGroup_1_3_1_1.eContents().get(1);
		private final Group cGroup_1_3_1_2 = (Group)cUnorderedGroup_1_3_1.eContents().get(2);
		private final Assignment cSortAssignment_1_3_1_2_0 = (Assignment)cGroup_1_3_1_2.eContents().get(0);
		private final Keyword cSortSortKeyword_1_3_1_2_0_0 = (Keyword)cSortAssignment_1_3_1_2_0.eContents().get(0);
		private final Keyword cCommaKeyword_1_3_1_2_1 = (Keyword)cGroup_1_3_1_2.eContents().get(1);
		private final Group cGroup_1_3_1_3 = (Group)cUnorderedGroup_1_3_1.eContents().get(3);
		private final Assignment cDeletionAssignment_1_3_1_3_0 = (Assignment)cGroup_1_3_1_3.eContents().get(0);
		private final Keyword cDeletionDeletionKeyword_1_3_1_3_0_0 = (Keyword)cDeletionAssignment_1_3_1_3_0.eContents().get(0);
		private final Keyword cCommaKeyword_1_3_1_3_1 = (Keyword)cGroup_1_3_1_3.eContents().get(1);
		private final Assignment cCreationAssignment_1_3_2 = (Assignment)cGroup_1_3.eContents().get(2);
		private final Keyword cCreationCreationKeyword_1_3_2_0 = (Keyword)cCreationAssignment_1_3_2.eContents().get(0);
		private final Group cGroup_1_4 = (Group)cAlternatives_1.eContents().get(4);
		private final Keyword cVerticalLineKeyword_1_4_0 = (Keyword)cGroup_1_4.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1_4_1 = (UnorderedGroup)cGroup_1_4.eContents().get(1);
		private final Group cGroup_1_4_1_0 = (Group)cUnorderedGroup_1_4_1.eContents().get(0);
		private final Assignment cGroupAssignment_1_4_1_0_0 = (Assignment)cGroup_1_4_1_0.eContents().get(0);
		private final Keyword cGroupGroupKeyword_1_4_1_0_0_0 = (Keyword)cGroupAssignment_1_4_1_0_0.eContents().get(0);
		private final Keyword cCommaKeyword_1_4_1_0_1 = (Keyword)cGroup_1_4_1_0.eContents().get(1);
		private final Group cGroup_1_4_1_1 = (Group)cUnorderedGroup_1_4_1.eContents().get(1);
		private final Assignment cFilterAssignment_1_4_1_1_0 = (Assignment)cGroup_1_4_1_1.eContents().get(0);
		private final Keyword cFilterFilterKeyword_1_4_1_1_0_0 = (Keyword)cFilterAssignment_1_4_1_1_0.eContents().get(0);
		private final Keyword cCommaKeyword_1_4_1_1_1 = (Keyword)cGroup_1_4_1_1.eContents().get(1);
		private final Group cGroup_1_4_1_2 = (Group)cUnorderedGroup_1_4_1.eContents().get(2);
		private final Assignment cSortAssignment_1_4_1_2_0 = (Assignment)cGroup_1_4_1_2.eContents().get(0);
		private final Keyword cSortSortKeyword_1_4_1_2_0_0 = (Keyword)cSortAssignment_1_4_1_2_0.eContents().get(0);
		private final Keyword cCommaKeyword_1_4_1_2_1 = (Keyword)cGroup_1_4_1_2.eContents().get(1);
		private final Group cGroup_1_4_1_3 = (Group)cUnorderedGroup_1_4_1.eContents().get(3);
		private final Assignment cCreationAssignment_1_4_1_3_0 = (Assignment)cGroup_1_4_1_3.eContents().get(0);
		private final Keyword cCreationCreationKeyword_1_4_1_3_0_0 = (Keyword)cCreationAssignment_1_4_1_3_0.eContents().get(0);
		private final Keyword cCommaKeyword_1_4_1_3_1 = (Keyword)cGroup_1_4_1_3.eContents().get(1);
		private final Assignment cDeletionAssignment_1_4_2 = (Assignment)cGroup_1_4.eContents().get(2);
		private final Keyword cDeletionDeletionKeyword_1_4_2_0 = (Keyword)cDeletionAssignment_1_4_2.eContents().get(0);
		
		//ClassMatcherModifier:
		//	{ClassMatcherModifier} ('|' ((filter?='filter' ',')? & (sort?='sort' ',')? & (creation?='creation' ',')? &
		//	(deletion?='deletion' ',')?) group?='group'
		//	| '|' ((group?='group' ',')? & (sort?='sort' ',')? & (creation?='creation' ',')? & (deletion?='deletion' ',')?)
		//	filter?='filter'
		//	| '|' ((group?='group' ',')? & (filter?='filter' ',')? & (creation?='creation' ',')? & (deletion?='deletion' ',')?)
		//	sort?='sort'
		//	| '|' ((group?='group' ',')? & (filter?='filter' ',')? & (sort?='sort' ',')? & (deletion?='deletion' ',')?)
		//	creation?='creation'
		//	| '|' ((group?='group' ',')? & (filter?='filter' ',')? & (sort?='sort' ',')? & (creation?='creation' ',')?)
		//	deletion?='deletion')?;
		@Override public ParserRule getRule() { return rule; }
		
		//{ClassMatcherModifier} ('|' ((filter?='filter' ',')? & (sort?='sort' ',')? & (creation?='creation' ',')? &
		//(deletion?='deletion' ',')?) group?='group' | '|' ((group?='group' ',')? & (sort?='sort' ',')? & (creation?='creation'
		//',')? & (deletion?='deletion' ',')?) filter?='filter' | '|' ((group?='group' ',')? & (filter?='filter' ',')? &
		//(creation?='creation' ',')? & (deletion?='deletion' ',')?) sort?='sort' | '|' ((group?='group' ',')? &
		//(filter?='filter' ',')? & (sort?='sort' ',')? & (deletion?='deletion' ',')?) creation?='creation' | '|'
		//((group?='group' ',')? & (filter?='filter' ',')? & (sort?='sort' ',')? & (creation?='creation' ',')?)
		//deletion?='deletion')?
		public Group getGroup() { return cGroup; }
		
		//{ClassMatcherModifier}
		public Action getClassMatcherModifierAction_0() { return cClassMatcherModifierAction_0; }
		
		//('|' ((filter?='filter' ',')? & (sort?='sort' ',')? & (creation?='creation' ',')? & (deletion?='deletion' ',')?)
		//group?='group' | '|' ((group?='group' ',')? & (sort?='sort' ',')? & (creation?='creation' ',')? &
		//(deletion?='deletion' ',')?) filter?='filter' | '|' ((group?='group' ',')? & (filter?='filter' ',')? &
		//(creation?='creation' ',')? & (deletion?='deletion' ',')?) sort?='sort' | '|' ((group?='group' ',')? &
		//(filter?='filter' ',')? & (sort?='sort' ',')? & (deletion?='deletion' ',')?) creation?='creation' | '|'
		//((group?='group' ',')? & (filter?='filter' ',')? & (sort?='sort' ',')? & (creation?='creation' ',')?)
		//deletion?='deletion')?
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'|' ((filter?='filter' ',')? & (sort?='sort' ',')? & (creation?='creation' ',')? & (deletion?='deletion' ',')?)
		//group?='group'
		public Group getGroup_1_0() { return cGroup_1_0; }
		
		//'|'
		public Keyword getVerticalLineKeyword_1_0_0() { return cVerticalLineKeyword_1_0_0; }
		
		//(filter?='filter' ',')? & (sort?='sort' ',')? & (creation?='creation' ',')? & (deletion?='deletion' ',')?
		public UnorderedGroup getUnorderedGroup_1_0_1() { return cUnorderedGroup_1_0_1; }
		
		//(filter?='filter' ',')?
		public Group getGroup_1_0_1_0() { return cGroup_1_0_1_0; }
		
		//filter?='filter'
		public Assignment getFilterAssignment_1_0_1_0_0() { return cFilterAssignment_1_0_1_0_0; }
		
		//'filter'
		public Keyword getFilterFilterKeyword_1_0_1_0_0_0() { return cFilterFilterKeyword_1_0_1_0_0_0; }
		
		//','
		public Keyword getCommaKeyword_1_0_1_0_1() { return cCommaKeyword_1_0_1_0_1; }
		
		//(sort?='sort' ',')?
		public Group getGroup_1_0_1_1() { return cGroup_1_0_1_1; }
		
		//sort?='sort'
		public Assignment getSortAssignment_1_0_1_1_0() { return cSortAssignment_1_0_1_1_0; }
		
		//'sort'
		public Keyword getSortSortKeyword_1_0_1_1_0_0() { return cSortSortKeyword_1_0_1_1_0_0; }
		
		//','
		public Keyword getCommaKeyword_1_0_1_1_1() { return cCommaKeyword_1_0_1_1_1; }
		
		//(creation?='creation' ',')?
		public Group getGroup_1_0_1_2() { return cGroup_1_0_1_2; }
		
		//creation?='creation'
		public Assignment getCreationAssignment_1_0_1_2_0() { return cCreationAssignment_1_0_1_2_0; }
		
		//'creation'
		public Keyword getCreationCreationKeyword_1_0_1_2_0_0() { return cCreationCreationKeyword_1_0_1_2_0_0; }
		
		//','
		public Keyword getCommaKeyword_1_0_1_2_1() { return cCommaKeyword_1_0_1_2_1; }
		
		//(deletion?='deletion' ',')?
		public Group getGroup_1_0_1_3() { return cGroup_1_0_1_3; }
		
		//deletion?='deletion'
		public Assignment getDeletionAssignment_1_0_1_3_0() { return cDeletionAssignment_1_0_1_3_0; }
		
		//'deletion'
		public Keyword getDeletionDeletionKeyword_1_0_1_3_0_0() { return cDeletionDeletionKeyword_1_0_1_3_0_0; }
		
		//','
		public Keyword getCommaKeyword_1_0_1_3_1() { return cCommaKeyword_1_0_1_3_1; }
		
		//group?='group'
		public Assignment getGroupAssignment_1_0_2() { return cGroupAssignment_1_0_2; }
		
		//'group'
		public Keyword getGroupGroupKeyword_1_0_2_0() { return cGroupGroupKeyword_1_0_2_0; }
		
		//'|' ((group?='group' ',')? & (sort?='sort' ',')? & (creation?='creation' ',')? & (deletion?='deletion' ',')?)
		//filter?='filter'
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//'|'
		public Keyword getVerticalLineKeyword_1_1_0() { return cVerticalLineKeyword_1_1_0; }
		
		//(group?='group' ',')? & (sort?='sort' ',')? & (creation?='creation' ',')? & (deletion?='deletion' ',')?
		public UnorderedGroup getUnorderedGroup_1_1_1() { return cUnorderedGroup_1_1_1; }
		
		//(group?='group' ',')?
		public Group getGroup_1_1_1_0() { return cGroup_1_1_1_0; }
		
		//group?='group'
		public Assignment getGroupAssignment_1_1_1_0_0() { return cGroupAssignment_1_1_1_0_0; }
		
		//'group'
		public Keyword getGroupGroupKeyword_1_1_1_0_0_0() { return cGroupGroupKeyword_1_1_1_0_0_0; }
		
		//','
		public Keyword getCommaKeyword_1_1_1_0_1() { return cCommaKeyword_1_1_1_0_1; }
		
		//(sort?='sort' ',')?
		public Group getGroup_1_1_1_1() { return cGroup_1_1_1_1; }
		
		//sort?='sort'
		public Assignment getSortAssignment_1_1_1_1_0() { return cSortAssignment_1_1_1_1_0; }
		
		//'sort'
		public Keyword getSortSortKeyword_1_1_1_1_0_0() { return cSortSortKeyword_1_1_1_1_0_0; }
		
		//','
		public Keyword getCommaKeyword_1_1_1_1_1() { return cCommaKeyword_1_1_1_1_1; }
		
		//(creation?='creation' ',')?
		public Group getGroup_1_1_1_2() { return cGroup_1_1_1_2; }
		
		//creation?='creation'
		public Assignment getCreationAssignment_1_1_1_2_0() { return cCreationAssignment_1_1_1_2_0; }
		
		//'creation'
		public Keyword getCreationCreationKeyword_1_1_1_2_0_0() { return cCreationCreationKeyword_1_1_1_2_0_0; }
		
		//','
		public Keyword getCommaKeyword_1_1_1_2_1() { return cCommaKeyword_1_1_1_2_1; }
		
		//(deletion?='deletion' ',')?
		public Group getGroup_1_1_1_3() { return cGroup_1_1_1_3; }
		
		//deletion?='deletion'
		public Assignment getDeletionAssignment_1_1_1_3_0() { return cDeletionAssignment_1_1_1_3_0; }
		
		//'deletion'
		public Keyword getDeletionDeletionKeyword_1_1_1_3_0_0() { return cDeletionDeletionKeyword_1_1_1_3_0_0; }
		
		//','
		public Keyword getCommaKeyword_1_1_1_3_1() { return cCommaKeyword_1_1_1_3_1; }
		
		//filter?='filter'
		public Assignment getFilterAssignment_1_1_2() { return cFilterAssignment_1_1_2; }
		
		//'filter'
		public Keyword getFilterFilterKeyword_1_1_2_0() { return cFilterFilterKeyword_1_1_2_0; }
		
		//'|' ((group?='group' ',')? & (filter?='filter' ',')? & (creation?='creation' ',')? & (deletion?='deletion' ',')?)
		//sort?='sort'
		public Group getGroup_1_2() { return cGroup_1_2; }
		
		//'|'
		public Keyword getVerticalLineKeyword_1_2_0() { return cVerticalLineKeyword_1_2_0; }
		
		//(group?='group' ',')? & (filter?='filter' ',')? & (creation?='creation' ',')? & (deletion?='deletion' ',')?
		public UnorderedGroup getUnorderedGroup_1_2_1() { return cUnorderedGroup_1_2_1; }
		
		//(group?='group' ',')?
		public Group getGroup_1_2_1_0() { return cGroup_1_2_1_0; }
		
		//group?='group'
		public Assignment getGroupAssignment_1_2_1_0_0() { return cGroupAssignment_1_2_1_0_0; }
		
		//'group'
		public Keyword getGroupGroupKeyword_1_2_1_0_0_0() { return cGroupGroupKeyword_1_2_1_0_0_0; }
		
		//','
		public Keyword getCommaKeyword_1_2_1_0_1() { return cCommaKeyword_1_2_1_0_1; }
		
		//(filter?='filter' ',')?
		public Group getGroup_1_2_1_1() { return cGroup_1_2_1_1; }
		
		//filter?='filter'
		public Assignment getFilterAssignment_1_2_1_1_0() { return cFilterAssignment_1_2_1_1_0; }
		
		//'filter'
		public Keyword getFilterFilterKeyword_1_2_1_1_0_0() { return cFilterFilterKeyword_1_2_1_1_0_0; }
		
		//','
		public Keyword getCommaKeyword_1_2_1_1_1() { return cCommaKeyword_1_2_1_1_1; }
		
		//(creation?='creation' ',')?
		public Group getGroup_1_2_1_2() { return cGroup_1_2_1_2; }
		
		//creation?='creation'
		public Assignment getCreationAssignment_1_2_1_2_0() { return cCreationAssignment_1_2_1_2_0; }
		
		//'creation'
		public Keyword getCreationCreationKeyword_1_2_1_2_0_0() { return cCreationCreationKeyword_1_2_1_2_0_0; }
		
		//','
		public Keyword getCommaKeyword_1_2_1_2_1() { return cCommaKeyword_1_2_1_2_1; }
		
		//(deletion?='deletion' ',')?
		public Group getGroup_1_2_1_3() { return cGroup_1_2_1_3; }
		
		//deletion?='deletion'
		public Assignment getDeletionAssignment_1_2_1_3_0() { return cDeletionAssignment_1_2_1_3_0; }
		
		//'deletion'
		public Keyword getDeletionDeletionKeyword_1_2_1_3_0_0() { return cDeletionDeletionKeyword_1_2_1_3_0_0; }
		
		//','
		public Keyword getCommaKeyword_1_2_1_3_1() { return cCommaKeyword_1_2_1_3_1; }
		
		//sort?='sort'
		public Assignment getSortAssignment_1_2_2() { return cSortAssignment_1_2_2; }
		
		//'sort'
		public Keyword getSortSortKeyword_1_2_2_0() { return cSortSortKeyword_1_2_2_0; }
		
		//'|' ((group?='group' ',')? & (filter?='filter' ',')? & (sort?='sort' ',')? & (deletion?='deletion' ',')?)
		//creation?='creation'
		public Group getGroup_1_3() { return cGroup_1_3; }
		
		//'|'
		public Keyword getVerticalLineKeyword_1_3_0() { return cVerticalLineKeyword_1_3_0; }
		
		//(group?='group' ',')? & (filter?='filter' ',')? & (sort?='sort' ',')? & (deletion?='deletion' ',')?
		public UnorderedGroup getUnorderedGroup_1_3_1() { return cUnorderedGroup_1_3_1; }
		
		//(group?='group' ',')?
		public Group getGroup_1_3_1_0() { return cGroup_1_3_1_0; }
		
		//group?='group'
		public Assignment getGroupAssignment_1_3_1_0_0() { return cGroupAssignment_1_3_1_0_0; }
		
		//'group'
		public Keyword getGroupGroupKeyword_1_3_1_0_0_0() { return cGroupGroupKeyword_1_3_1_0_0_0; }
		
		//','
		public Keyword getCommaKeyword_1_3_1_0_1() { return cCommaKeyword_1_3_1_0_1; }
		
		//(filter?='filter' ',')?
		public Group getGroup_1_3_1_1() { return cGroup_1_3_1_1; }
		
		//filter?='filter'
		public Assignment getFilterAssignment_1_3_1_1_0() { return cFilterAssignment_1_3_1_1_0; }
		
		//'filter'
		public Keyword getFilterFilterKeyword_1_3_1_1_0_0() { return cFilterFilterKeyword_1_3_1_1_0_0; }
		
		//','
		public Keyword getCommaKeyword_1_3_1_1_1() { return cCommaKeyword_1_3_1_1_1; }
		
		//(sort?='sort' ',')?
		public Group getGroup_1_3_1_2() { return cGroup_1_3_1_2; }
		
		//sort?='sort'
		public Assignment getSortAssignment_1_3_1_2_0() { return cSortAssignment_1_3_1_2_0; }
		
		//'sort'
		public Keyword getSortSortKeyword_1_3_1_2_0_0() { return cSortSortKeyword_1_3_1_2_0_0; }
		
		//','
		public Keyword getCommaKeyword_1_3_1_2_1() { return cCommaKeyword_1_3_1_2_1; }
		
		//(deletion?='deletion' ',')?
		public Group getGroup_1_3_1_3() { return cGroup_1_3_1_3; }
		
		//deletion?='deletion'
		public Assignment getDeletionAssignment_1_3_1_3_0() { return cDeletionAssignment_1_3_1_3_0; }
		
		//'deletion'
		public Keyword getDeletionDeletionKeyword_1_3_1_3_0_0() { return cDeletionDeletionKeyword_1_3_1_3_0_0; }
		
		//','
		public Keyword getCommaKeyword_1_3_1_3_1() { return cCommaKeyword_1_3_1_3_1; }
		
		//creation?='creation'
		public Assignment getCreationAssignment_1_3_2() { return cCreationAssignment_1_3_2; }
		
		//'creation'
		public Keyword getCreationCreationKeyword_1_3_2_0() { return cCreationCreationKeyword_1_3_2_0; }
		
		//'|' ((group?='group' ',')? & (filter?='filter' ',')? & (sort?='sort' ',')? & (creation?='creation' ',')?)
		//deletion?='deletion'
		public Group getGroup_1_4() { return cGroup_1_4; }
		
		//'|'
		public Keyword getVerticalLineKeyword_1_4_0() { return cVerticalLineKeyword_1_4_0; }
		
		//(group?='group' ',')? & (filter?='filter' ',')? & (sort?='sort' ',')? & (creation?='creation' ',')?
		public UnorderedGroup getUnorderedGroup_1_4_1() { return cUnorderedGroup_1_4_1; }
		
		//(group?='group' ',')?
		public Group getGroup_1_4_1_0() { return cGroup_1_4_1_0; }
		
		//group?='group'
		public Assignment getGroupAssignment_1_4_1_0_0() { return cGroupAssignment_1_4_1_0_0; }
		
		//'group'
		public Keyword getGroupGroupKeyword_1_4_1_0_0_0() { return cGroupGroupKeyword_1_4_1_0_0_0; }
		
		//','
		public Keyword getCommaKeyword_1_4_1_0_1() { return cCommaKeyword_1_4_1_0_1; }
		
		//(filter?='filter' ',')?
		public Group getGroup_1_4_1_1() { return cGroup_1_4_1_1; }
		
		//filter?='filter'
		public Assignment getFilterAssignment_1_4_1_1_0() { return cFilterAssignment_1_4_1_1_0; }
		
		//'filter'
		public Keyword getFilterFilterKeyword_1_4_1_1_0_0() { return cFilterFilterKeyword_1_4_1_1_0_0; }
		
		//','
		public Keyword getCommaKeyword_1_4_1_1_1() { return cCommaKeyword_1_4_1_1_1; }
		
		//(sort?='sort' ',')?
		public Group getGroup_1_4_1_2() { return cGroup_1_4_1_2; }
		
		//sort?='sort'
		public Assignment getSortAssignment_1_4_1_2_0() { return cSortAssignment_1_4_1_2_0; }
		
		//'sort'
		public Keyword getSortSortKeyword_1_4_1_2_0_0() { return cSortSortKeyword_1_4_1_2_0_0; }
		
		//','
		public Keyword getCommaKeyword_1_4_1_2_1() { return cCommaKeyword_1_4_1_2_1; }
		
		//(creation?='creation' ',')?
		public Group getGroup_1_4_1_3() { return cGroup_1_4_1_3; }
		
		//creation?='creation'
		public Assignment getCreationAssignment_1_4_1_3_0() { return cCreationAssignment_1_4_1_3_0; }
		
		//'creation'
		public Keyword getCreationCreationKeyword_1_4_1_3_0_0() { return cCreationCreationKeyword_1_4_1_3_0_0; }
		
		//','
		public Keyword getCommaKeyword_1_4_1_3_1() { return cCommaKeyword_1_4_1_3_1; }
		
		//deletion?='deletion'
		public Assignment getDeletionAssignment_1_4_2() { return cDeletionAssignment_1_4_2; }
		
		//'deletion'
		public Keyword getDeletionDeletionKeyword_1_4_2_0() { return cDeletionDeletionKeyword_1_4_2_0; }
	}
	public class FeatureMappingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.ubt.ai1.m2m.bxtenddsl.BXtendDSL.FeatureMapping");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Assignment cSrcFeaturesAssignment_0_0 = (Assignment)cAlternatives_0.eContents().get(0);
		private final RuleCall cSrcFeaturesSrcMappingFeatureParserRuleCall_0_0_0 = (RuleCall)cSrcFeaturesAssignment_0_0.eContents().get(0);
		private final Assignment cSrcClassesAssignment_0_1 = (Assignment)cAlternatives_0.eContents().get(1);
		private final CrossReference cSrcClassesClassMatcherCrossReference_0_1_0 = (CrossReference)cSrcClassesAssignment_0_1.eContents().get(0);
		private final RuleCall cSrcClassesClassMatcherIDTerminalRuleCall_0_1_0_1 = (RuleCall)cSrcClassesClassMatcherCrossReference_0_1_0.eContents().get(1);
		private final Assignment cDirectionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cDirectionDirectionEnumRuleCall_1_0 = (RuleCall)cDirectionAssignment_1.eContents().get(0);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final Assignment cTrgFeaturesAssignment_2_0 = (Assignment)cAlternatives_2.eContents().get(0);
		private final RuleCall cTrgFeaturesTrgMappingFeatureParserRuleCall_2_0_0 = (RuleCall)cTrgFeaturesAssignment_2_0.eContents().get(0);
		private final Assignment cTrgClassesAssignment_2_1 = (Assignment)cAlternatives_2.eContents().get(1);
		private final CrossReference cTrgClassesClassMatcherCrossReference_2_1_0 = (CrossReference)cTrgClassesAssignment_2_1.eContents().get(0);
		private final RuleCall cTrgClassesClassMatcherIDTerminalRuleCall_2_1_0_1 = (RuleCall)cTrgClassesClassMatcherCrossReference_2_1_0.eContents().get(1);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//FeatureMapping:
		//	(srcFeatures+=SrcMappingFeature | srcClasses+=[ClassMatcher])+
		//	direction=Direction (trgFeatures+=TrgMappingFeature | trgClasses+=[ClassMatcher])+ ';';
		@Override public ParserRule getRule() { return rule; }
		
		//(srcFeatures+=SrcMappingFeature | srcClasses+=[ClassMatcher])+ direction=Direction (trgFeatures+=TrgMappingFeature |
		//trgClasses+=[ClassMatcher])+ ';'
		public Group getGroup() { return cGroup; }
		
		//(srcFeatures+=SrcMappingFeature | srcClasses+=[ClassMatcher])+
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//srcFeatures+=SrcMappingFeature
		public Assignment getSrcFeaturesAssignment_0_0() { return cSrcFeaturesAssignment_0_0; }
		
		//SrcMappingFeature
		public RuleCall getSrcFeaturesSrcMappingFeatureParserRuleCall_0_0_0() { return cSrcFeaturesSrcMappingFeatureParserRuleCall_0_0_0; }
		
		//srcClasses+=[ClassMatcher]
		public Assignment getSrcClassesAssignment_0_1() { return cSrcClassesAssignment_0_1; }
		
		//[ClassMatcher]
		public CrossReference getSrcClassesClassMatcherCrossReference_0_1_0() { return cSrcClassesClassMatcherCrossReference_0_1_0; }
		
		//ID
		public RuleCall getSrcClassesClassMatcherIDTerminalRuleCall_0_1_0_1() { return cSrcClassesClassMatcherIDTerminalRuleCall_0_1_0_1; }
		
		//direction=Direction
		public Assignment getDirectionAssignment_1() { return cDirectionAssignment_1; }
		
		//Direction
		public RuleCall getDirectionDirectionEnumRuleCall_1_0() { return cDirectionDirectionEnumRuleCall_1_0; }
		
		//(trgFeatures+=TrgMappingFeature | trgClasses+=[ClassMatcher])+
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//trgFeatures+=TrgMappingFeature
		public Assignment getTrgFeaturesAssignment_2_0() { return cTrgFeaturesAssignment_2_0; }
		
		//TrgMappingFeature
		public RuleCall getTrgFeaturesTrgMappingFeatureParserRuleCall_2_0_0() { return cTrgFeaturesTrgMappingFeatureParserRuleCall_2_0_0; }
		
		//trgClasses+=[ClassMatcher]
		public Assignment getTrgClassesAssignment_2_1() { return cTrgClassesAssignment_2_1; }
		
		//[ClassMatcher]
		public CrossReference getTrgClassesClassMatcherCrossReference_2_1_0() { return cTrgClassesClassMatcherCrossReference_2_1_0; }
		
		//ID
		public RuleCall getTrgClassesClassMatcherIDTerminalRuleCall_2_1_0_1() { return cTrgClassesClassMatcherIDTerminalRuleCall_2_1_0_1; }
		
		//';'
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}
	public class MappingFeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.ubt.ai1.m2m.bxtenddsl.BXtendDSL.MappingFeature");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSrcMappingFeatureParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTrgMappingFeatureParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//MappingFeature:
		//	SrcMappingFeature | TrgMappingFeature;
		@Override public ParserRule getRule() { return rule; }
		
		//SrcMappingFeature | TrgMappingFeature
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//SrcMappingFeature
		public RuleCall getSrcMappingFeatureParserRuleCall_0() { return cSrcMappingFeatureParserRuleCall_0; }
		
		//TrgMappingFeature
		public RuleCall getTrgMappingFeatureParserRuleCall_1() { return cTrgMappingFeatureParserRuleCall_1; }
	}
	public class SrcMappingFeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.ubt.ai1.m2m.bxtenddsl.BXtendDSL.SrcMappingFeature");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cFeatureAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final CrossReference cFeatureEStructuralFeatureCrossReference_0_0 = (CrossReference)cFeatureAssignment_0.eContents().get(0);
		private final RuleCall cFeatureEStructuralFeatureFeatureAccessParserRuleCall_0_0_1 = (RuleCall)cFeatureEStructuralFeatureCrossReference_0_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Assignment cCorrAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final Keyword cCorrLeftCurlyBracketKeyword_1_0_0 = (Keyword)cCorrAssignment_1_0.eContents().get(0);
		private final Assignment cFeatureAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final CrossReference cFeatureEStructuralFeatureCrossReference_1_1_0 = (CrossReference)cFeatureAssignment_1_1.eContents().get(0);
		private final RuleCall cFeatureEStructuralFeatureFeatureAccessParserRuleCall_1_1_0_1 = (RuleCall)cFeatureEStructuralFeatureCrossReference_1_1_0.eContents().get(1);
		private final Keyword cColonKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Assignment cCorrsAssignment_1_3 = (Assignment)cGroup_1.eContents().get(3);
		private final RuleCall cCorrsCorrespondenceParserRuleCall_1_3_0 = (RuleCall)cCorrsAssignment_1_3.eContents().get(0);
		private final Group cGroup_1_4 = (Group)cGroup_1.eContents().get(4);
		private final Keyword cCommaKeyword_1_4_0 = (Keyword)cGroup_1_4.eContents().get(0);
		private final Assignment cCorrsAssignment_1_4_1 = (Assignment)cGroup_1_4.eContents().get(1);
		private final RuleCall cCorrsCorrespondenceParserRuleCall_1_4_1_0 = (RuleCall)cCorrsAssignment_1_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_1_5 = (Keyword)cGroup_1.eContents().get(5);
		
		//SrcMappingFeature:
		//	feature=[EStructuralFeature|FeatureAccess] | corr?='{' feature=[EStructuralFeature|FeatureAccess] ':'
		//	corrs+=Correspondence (',' corrs+=Correspondence)* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//feature=[EStructuralFeature|FeatureAccess] | corr?='{' feature=[EStructuralFeature|FeatureAccess] ':'
		//corrs+=Correspondence (',' corrs+=Correspondence)* '}'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//feature=[EStructuralFeature|FeatureAccess]
		public Assignment getFeatureAssignment_0() { return cFeatureAssignment_0; }
		
		//[EStructuralFeature|FeatureAccess]
		public CrossReference getFeatureEStructuralFeatureCrossReference_0_0() { return cFeatureEStructuralFeatureCrossReference_0_0; }
		
		//FeatureAccess
		public RuleCall getFeatureEStructuralFeatureFeatureAccessParserRuleCall_0_0_1() { return cFeatureEStructuralFeatureFeatureAccessParserRuleCall_0_0_1; }
		
		//corr?='{' feature=[EStructuralFeature|FeatureAccess] ':' corrs+=Correspondence (',' corrs+=Correspondence)* '}'
		public Group getGroup_1() { return cGroup_1; }
		
		//corr?='{'
		public Assignment getCorrAssignment_1_0() { return cCorrAssignment_1_0; }
		
		//'{'
		public Keyword getCorrLeftCurlyBracketKeyword_1_0_0() { return cCorrLeftCurlyBracketKeyword_1_0_0; }
		
		//feature=[EStructuralFeature|FeatureAccess]
		public Assignment getFeatureAssignment_1_1() { return cFeatureAssignment_1_1; }
		
		//[EStructuralFeature|FeatureAccess]
		public CrossReference getFeatureEStructuralFeatureCrossReference_1_1_0() { return cFeatureEStructuralFeatureCrossReference_1_1_0; }
		
		//FeatureAccess
		public RuleCall getFeatureEStructuralFeatureFeatureAccessParserRuleCall_1_1_0_1() { return cFeatureEStructuralFeatureFeatureAccessParserRuleCall_1_1_0_1; }
		
		//':'
		public Keyword getColonKeyword_1_2() { return cColonKeyword_1_2; }
		
		//corrs+=Correspondence
		public Assignment getCorrsAssignment_1_3() { return cCorrsAssignment_1_3; }
		
		//Correspondence
		public RuleCall getCorrsCorrespondenceParserRuleCall_1_3_0() { return cCorrsCorrespondenceParserRuleCall_1_3_0; }
		
		//(',' corrs+=Correspondence)*
		public Group getGroup_1_4() { return cGroup_1_4; }
		
		//','
		public Keyword getCommaKeyword_1_4_0() { return cCommaKeyword_1_4_0; }
		
		//corrs+=Correspondence
		public Assignment getCorrsAssignment_1_4_1() { return cCorrsAssignment_1_4_1; }
		
		//Correspondence
		public RuleCall getCorrsCorrespondenceParserRuleCall_1_4_1_0() { return cCorrsCorrespondenceParserRuleCall_1_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_1_5() { return cRightCurlyBracketKeyword_1_5; }
	}
	public class TrgMappingFeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.ubt.ai1.m2m.bxtenddsl.BXtendDSL.TrgMappingFeature");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cFeatureAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final CrossReference cFeatureEStructuralFeatureCrossReference_0_0 = (CrossReference)cFeatureAssignment_0.eContents().get(0);
		private final RuleCall cFeatureEStructuralFeatureFeatureAccessParserRuleCall_0_0_1 = (RuleCall)cFeatureEStructuralFeatureCrossReference_0_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Assignment cCorrAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final Keyword cCorrLeftCurlyBracketKeyword_1_0_0 = (Keyword)cCorrAssignment_1_0.eContents().get(0);
		private final Assignment cFeatureAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final CrossReference cFeatureEStructuralFeatureCrossReference_1_1_0 = (CrossReference)cFeatureAssignment_1_1.eContents().get(0);
		private final RuleCall cFeatureEStructuralFeatureFeatureAccessParserRuleCall_1_1_0_1 = (RuleCall)cFeatureEStructuralFeatureCrossReference_1_1_0.eContents().get(1);
		private final Keyword cColonKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Assignment cCorrsAssignment_1_3 = (Assignment)cGroup_1.eContents().get(3);
		private final RuleCall cCorrsCorrespondenceParserRuleCall_1_3_0 = (RuleCall)cCorrsAssignment_1_3.eContents().get(0);
		private final Group cGroup_1_4 = (Group)cGroup_1.eContents().get(4);
		private final Keyword cCommaKeyword_1_4_0 = (Keyword)cGroup_1_4.eContents().get(0);
		private final Assignment cCorrsAssignment_1_4_1 = (Assignment)cGroup_1_4.eContents().get(1);
		private final RuleCall cCorrsCorrespondenceParserRuleCall_1_4_1_0 = (RuleCall)cCorrsAssignment_1_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_1_5 = (Keyword)cGroup_1.eContents().get(5);
		
		//TrgMappingFeature:
		//	feature=[EStructuralFeature|FeatureAccess] | corr?='{' feature=[EStructuralFeature|FeatureAccess] ':'
		//	corrs+=Correspondence (',' corrs+=Correspondence)* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//feature=[EStructuralFeature|FeatureAccess] | corr?='{' feature=[EStructuralFeature|FeatureAccess] ':'
		//corrs+=Correspondence (',' corrs+=Correspondence)* '}'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//feature=[EStructuralFeature|FeatureAccess]
		public Assignment getFeatureAssignment_0() { return cFeatureAssignment_0; }
		
		//[EStructuralFeature|FeatureAccess]
		public CrossReference getFeatureEStructuralFeatureCrossReference_0_0() { return cFeatureEStructuralFeatureCrossReference_0_0; }
		
		//FeatureAccess
		public RuleCall getFeatureEStructuralFeatureFeatureAccessParserRuleCall_0_0_1() { return cFeatureEStructuralFeatureFeatureAccessParserRuleCall_0_0_1; }
		
		//corr?='{' feature=[EStructuralFeature|FeatureAccess] ':' corrs+=Correspondence (',' corrs+=Correspondence)* '}'
		public Group getGroup_1() { return cGroup_1; }
		
		//corr?='{'
		public Assignment getCorrAssignment_1_0() { return cCorrAssignment_1_0; }
		
		//'{'
		public Keyword getCorrLeftCurlyBracketKeyword_1_0_0() { return cCorrLeftCurlyBracketKeyword_1_0_0; }
		
		//feature=[EStructuralFeature|FeatureAccess]
		public Assignment getFeatureAssignment_1_1() { return cFeatureAssignment_1_1; }
		
		//[EStructuralFeature|FeatureAccess]
		public CrossReference getFeatureEStructuralFeatureCrossReference_1_1_0() { return cFeatureEStructuralFeatureCrossReference_1_1_0; }
		
		//FeatureAccess
		public RuleCall getFeatureEStructuralFeatureFeatureAccessParserRuleCall_1_1_0_1() { return cFeatureEStructuralFeatureFeatureAccessParserRuleCall_1_1_0_1; }
		
		//':'
		public Keyword getColonKeyword_1_2() { return cColonKeyword_1_2; }
		
		//corrs+=Correspondence
		public Assignment getCorrsAssignment_1_3() { return cCorrsAssignment_1_3; }
		
		//Correspondence
		public RuleCall getCorrsCorrespondenceParserRuleCall_1_3_0() { return cCorrsCorrespondenceParserRuleCall_1_3_0; }
		
		//(',' corrs+=Correspondence)*
		public Group getGroup_1_4() { return cGroup_1_4; }
		
		//','
		public Keyword getCommaKeyword_1_4_0() { return cCommaKeyword_1_4_0; }
		
		//corrs+=Correspondence
		public Assignment getCorrsAssignment_1_4_1() { return cCorrsAssignment_1_4_1; }
		
		//Correspondence
		public RuleCall getCorrsCorrespondenceParserRuleCall_1_4_1_0() { return cCorrsCorrespondenceParserRuleCall_1_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_1_5() { return cRightCurlyBracketKeyword_1_5; }
	}
	public class CorrespondenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.ubt.ai1.m2m.bxtenddsl.BXtendDSL.Correspondence");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cRuleAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cRuleTransformationRuleCrossReference_0_0 = (CrossReference)cRuleAssignment_0.eContents().get(0);
		private final RuleCall cRuleTransformationRuleIDTerminalRuleCall_0_0_1 = (RuleCall)cRuleTransformationRuleCrossReference_0_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cMatchersAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final CrossReference cMatchersClassMatcherCrossReference_1_1_0 = (CrossReference)cMatchersAssignment_1_1.eContents().get(0);
		private final RuleCall cMatchersClassMatcherIDTerminalRuleCall_1_1_0_1 = (RuleCall)cMatchersClassMatcherCrossReference_1_1_0.eContents().get(1);
		private final Group cGroup_1_2 = (Group)cGroup_1.eContents().get(2);
		private final Keyword cCommaKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Assignment cMatchersAssignment_1_2_1 = (Assignment)cGroup_1_2.eContents().get(1);
		private final CrossReference cMatchersClassMatcherCrossReference_1_2_1_0 = (CrossReference)cMatchersAssignment_1_2_1.eContents().get(0);
		private final RuleCall cMatchersClassMatcherIDTerminalRuleCall_1_2_1_0_1 = (RuleCall)cMatchersClassMatcherCrossReference_1_2_1_0.eContents().get(1);
		private final Keyword cRightSquareBracketKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		
		//Correspondence:
		//	rule=[TransformationRule] ('[' matchers+=[ClassMatcher] (',' matchers+=[ClassMatcher])* ']')?;
		@Override public ParserRule getRule() { return rule; }
		
		//rule=[TransformationRule] ('[' matchers+=[ClassMatcher] (',' matchers+=[ClassMatcher])* ']')?
		public Group getGroup() { return cGroup; }
		
		//rule=[TransformationRule]
		public Assignment getRuleAssignment_0() { return cRuleAssignment_0; }
		
		//[TransformationRule]
		public CrossReference getRuleTransformationRuleCrossReference_0_0() { return cRuleTransformationRuleCrossReference_0_0; }
		
		//ID
		public RuleCall getRuleTransformationRuleIDTerminalRuleCall_0_0_1() { return cRuleTransformationRuleIDTerminalRuleCall_0_0_1; }
		
		//('[' matchers+=[ClassMatcher] (',' matchers+=[ClassMatcher])* ']')?
		public Group getGroup_1() { return cGroup_1; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_1_0() { return cLeftSquareBracketKeyword_1_0; }
		
		//matchers+=[ClassMatcher]
		public Assignment getMatchersAssignment_1_1() { return cMatchersAssignment_1_1; }
		
		//[ClassMatcher]
		public CrossReference getMatchersClassMatcherCrossReference_1_1_0() { return cMatchersClassMatcherCrossReference_1_1_0; }
		
		//ID
		public RuleCall getMatchersClassMatcherIDTerminalRuleCall_1_1_0_1() { return cMatchersClassMatcherIDTerminalRuleCall_1_1_0_1; }
		
		//(',' matchers+=[ClassMatcher])*
		public Group getGroup_1_2() { return cGroup_1_2; }
		
		//','
		public Keyword getCommaKeyword_1_2_0() { return cCommaKeyword_1_2_0; }
		
		//matchers+=[ClassMatcher]
		public Assignment getMatchersAssignment_1_2_1() { return cMatchersAssignment_1_2_1; }
		
		//[ClassMatcher]
		public CrossReference getMatchersClassMatcherCrossReference_1_2_1_0() { return cMatchersClassMatcherCrossReference_1_2_1_0; }
		
		//ID
		public RuleCall getMatchersClassMatcherIDTerminalRuleCall_1_2_1_0_1() { return cMatchersClassMatcherIDTerminalRuleCall_1_2_1_0_1; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_1_3() { return cRightSquareBracketKeyword_1_3; }
	}
	public class FeatureAccessElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "de.ubt.ai1.m2m.bxtenddsl.BXtendDSL.FeatureAccess");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//FeatureAccess:
		//	ID (=> '.' ID)+;
		@Override public ParserRule getRule() { return rule; }
		
		//ID (=> '.' ID)+
		public Group getGroup() { return cGroup; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//(=> '.' ID)+
		public Group getGroup_1() { return cGroup_1; }
		
		//=> '.'
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	
	public class DirectionElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "de.ubt.ai1.m2m.bxtenddsl.BXtendDSL.Direction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cFWDEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cFWDHyphenMinusHyphenMinusGreaterThanSignKeyword_0_0 = (Keyword)cFWDEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cBWDEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cBWDLessThanSignHyphenMinusHyphenMinusKeyword_1_0 = (Keyword)cBWDEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cBXEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cBXLessThanSignHyphenMinusHyphenMinusGreaterThanSignKeyword_2_0 = (Keyword)cBXEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum Direction:
		//	FWD='-->' | BWD='<--' | BX='<-->';
		public EnumRule getRule() { return rule; }
		
		//FWD='-->' | BWD='<--' | BX='<-->'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//FWD='-->'
		public EnumLiteralDeclaration getFWDEnumLiteralDeclaration_0() { return cFWDEnumLiteralDeclaration_0; }
		
		//'-->'
		public Keyword getFWDHyphenMinusHyphenMinusGreaterThanSignKeyword_0_0() { return cFWDHyphenMinusHyphenMinusGreaterThanSignKeyword_0_0; }
		
		//BWD='<--'
		public EnumLiteralDeclaration getBWDEnumLiteralDeclaration_1() { return cBWDEnumLiteralDeclaration_1; }
		
		//'<--'
		public Keyword getBWDLessThanSignHyphenMinusHyphenMinusKeyword_1_0() { return cBWDLessThanSignHyphenMinusHyphenMinusKeyword_1_0; }
		
		//BX='<-->'
		public EnumLiteralDeclaration getBXEnumLiteralDeclaration_2() { return cBXEnumLiteralDeclaration_2; }
		
		//'<-->'
		public Keyword getBXLessThanSignHyphenMinusHyphenMinusGreaterThanSignKeyword_2_0() { return cBXLessThanSignHyphenMinusHyphenMinusGreaterThanSignKeyword_2_0; }
	}
	
	private final BXtendDSLElements pBXtendDSL;
	private final MetamodelsElements pMetamodels;
	private final CustomizedElementElements pCustomizedElement;
	private final CustomizedGetterElements pCustomizedGetter;
	private final CustomizedSetterElements pCustomizedSetter;
	private final ConfigElements pConfig;
	private final TransformationRuleElements pTransformationRule;
	private final ClassMatcherElements pClassMatcher;
	private final SrcClassMatcherElements pSrcClassMatcher;
	private final TrgClassMatcherElements pTrgClassMatcher;
	private final ClassMatcherModifierElements pClassMatcherModifier;
	private final FeatureMappingElements pFeatureMapping;
	private final MappingFeatureElements pMappingFeature;
	private final SrcMappingFeatureElements pSrcMappingFeature;
	private final TrgMappingFeatureElements pTrgMappingFeature;
	private final CorrespondenceElements pCorrespondence;
	private final DirectionElements eDirection;
	private final FeatureAccessElements pFeatureAccess;
	private final TerminalRule tID;
	private final TerminalRule tSTRING;
	private final TerminalRule tWS;
	private final TerminalRule tINDENTATION;
	private final TerminalRule tSL_COMMENT;
	private final TerminalRule tTAB_INDENTED_BLOCK_BEGIN;
	private final TerminalRule tTAB_INDENTED_BLOCK_END;
	
	private final Grammar grammar;

	@Inject
	public BXtendDSLGrammarAccess(GrammarProvider grammarProvider) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.pBXtendDSL = new BXtendDSLElements();
		this.pMetamodels = new MetamodelsElements();
		this.pCustomizedElement = new CustomizedElementElements();
		this.pCustomizedGetter = new CustomizedGetterElements();
		this.pCustomizedSetter = new CustomizedSetterElements();
		this.pConfig = new ConfigElements();
		this.pTransformationRule = new TransformationRuleElements();
		this.pClassMatcher = new ClassMatcherElements();
		this.pSrcClassMatcher = new SrcClassMatcherElements();
		this.pTrgClassMatcher = new TrgClassMatcherElements();
		this.pClassMatcherModifier = new ClassMatcherModifierElements();
		this.pFeatureMapping = new FeatureMappingElements();
		this.pMappingFeature = new MappingFeatureElements();
		this.pSrcMappingFeature = new SrcMappingFeatureElements();
		this.pTrgMappingFeature = new TrgMappingFeatureElements();
		this.pCorrespondence = new CorrespondenceElements();
		this.eDirection = new DirectionElements();
		this.pFeatureAccess = new FeatureAccessElements();
		this.tID = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.ubt.ai1.m2m.bxtenddsl.BXtendDSL.ID");
		this.tSTRING = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.ubt.ai1.m2m.bxtenddsl.BXtendDSL.STRING");
		this.tWS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.ubt.ai1.m2m.bxtenddsl.BXtendDSL.WS");
		this.tINDENTATION = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.ubt.ai1.m2m.bxtenddsl.BXtendDSL.INDENTATION");
		this.tSL_COMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.ubt.ai1.m2m.bxtenddsl.BXtendDSL.SL_COMMENT");
		this.tTAB_INDENTED_BLOCK_BEGIN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.ubt.ai1.m2m.bxtenddsl.BXtendDSL.TAB_INDENTED_BLOCK_BEGIN");
		this.tTAB_INDENTED_BLOCK_END = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "de.ubt.ai1.m2m.bxtenddsl.BXtendDSL.TAB_INDENTED_BLOCK_END");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.ubt.ai1.m2m.bxtenddsl.BXtendDSL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	
	//BXtendDSL:
	//	metamodels=Metamodels
	//	config=Config
	//	rules+=TransformationRule*;
	public BXtendDSLElements getBXtendDSLAccess() {
		return pBXtendDSL;
	}
	
	public ParserRule getBXtendDSLRule() {
		return getBXtendDSLAccess().getRule();
	}
	
	//Metamodels:
	//	'sourcemodel' sourcemodel=STRING (TAB_INDENTED_BLOCK_BEGIN
	//	customizedSrcElements+=CustomizedElement+
	//	TAB_INDENTED_BLOCK_END)?
	//	'targetmodel' targetmodel=STRING (TAB_INDENTED_BLOCK_BEGIN
	//	customizedTrgElements+=CustomizedElement+
	//	TAB_INDENTED_BLOCK_END)?;
	public MetamodelsElements getMetamodelsAccess() {
		return pMetamodels;
	}
	
	public ParserRule getMetamodelsRule() {
		return getMetamodelsAccess().getRule();
	}
	
	//CustomizedElement:
	//	CustomizedGetter | CustomizedSetter;
	public CustomizedElementElements getCustomizedElementAccess() {
		return pCustomizedElement;
	}
	
	public ParserRule getCustomizedElementRule() {
		return getCustomizedElementAccess().getRule();
	}
	
	//CustomizedGetter:
	//	'get' element=[EStructuralFeature|FeatureAccess] 'as' customId=ID;
	public CustomizedGetterElements getCustomizedGetterAccess() {
		return pCustomizedGetter;
	}
	
	public ParserRule getCustomizedGetterRule() {
		return getCustomizedGetterAccess().getRule();
	}
	
	//CustomizedSetter:
	//	'set' element=[EStructuralFeature|FeatureAccess] 'as' customId=ID;
	public CustomizedSetterElements getCustomizedSetterAccess() {
		return pCustomizedSetter;
	}
	
	public ParserRule getCustomizedSetterRule() {
		return getCustomizedSetterAccess().getRule();
	}
	
	//Config:
	//	{Config} ('options'
	//	TAB_INDENTED_BLOCK_BEGIN
	//	options+=ID+
	//	TAB_INDENTED_BLOCK_END)?;
	public ConfigElements getConfigAccess() {
		return pConfig;
	}
	
	public ParserRule getConfigRule() {
		return getConfigAccess().getRule();
	}
	
	//TransformationRule:
	//	'rule' name=ID
	//	TAB_INDENTED_BLOCK_BEGIN
	//	'src' srcMatcher+=SrcClassMatcher (TAB_INDENTED_BLOCK_BEGIN
	//	srcMatcher+=SrcClassMatcher+
	//	TAB_INDENTED_BLOCK_END)?
	//	'trg' trgMatcher+=TrgClassMatcher (TAB_INDENTED_BLOCK_BEGIN
	//	trgMatcher+=TrgClassMatcher+
	//	TAB_INDENTED_BLOCK_END)?
	//	mappings+=FeatureMapping*
	//	TAB_INDENTED_BLOCK_END;
	public TransformationRuleElements getTransformationRuleAccess() {
		return pTransformationRule;
	}
	
	public ParserRule getTransformationRuleRule() {
		return getTransformationRuleAccess().getRule();
	}
	
	//ClassMatcher:
	//	SrcClassMatcher | TrgClassMatcher;
	public ClassMatcherElements getClassMatcherAccess() {
		return pClassMatcher;
	}
	
	public ParserRule getClassMatcherRule() {
		return getClassMatcherAccess().getRule();
	}
	
	//SrcClassMatcher:
	//	clazz=[EClass] name=ID modifier=ClassMatcherModifier ';';
	public SrcClassMatcherElements getSrcClassMatcherAccess() {
		return pSrcClassMatcher;
	}
	
	public ParserRule getSrcClassMatcherRule() {
		return getSrcClassMatcherAccess().getRule();
	}
	
	//TrgClassMatcher:
	//	clazz=[EClass] name=ID modifier=ClassMatcherModifier ';';
	public TrgClassMatcherElements getTrgClassMatcherAccess() {
		return pTrgClassMatcher;
	}
	
	public ParserRule getTrgClassMatcherRule() {
		return getTrgClassMatcherAccess().getRule();
	}
	
	//ClassMatcherModifier:
	//	{ClassMatcherModifier} ('|' ((filter?='filter' ',')? & (sort?='sort' ',')? & (creation?='creation' ',')? &
	//	(deletion?='deletion' ',')?) group?='group'
	//	| '|' ((group?='group' ',')? & (sort?='sort' ',')? & (creation?='creation' ',')? & (deletion?='deletion' ',')?)
	//	filter?='filter'
	//	| '|' ((group?='group' ',')? & (filter?='filter' ',')? & (creation?='creation' ',')? & (deletion?='deletion' ',')?)
	//	sort?='sort'
	//	| '|' ((group?='group' ',')? & (filter?='filter' ',')? & (sort?='sort' ',')? & (deletion?='deletion' ',')?)
	//	creation?='creation'
	//	| '|' ((group?='group' ',')? & (filter?='filter' ',')? & (sort?='sort' ',')? & (creation?='creation' ',')?)
	//	deletion?='deletion')?;
	public ClassMatcherModifierElements getClassMatcherModifierAccess() {
		return pClassMatcherModifier;
	}
	
	public ParserRule getClassMatcherModifierRule() {
		return getClassMatcherModifierAccess().getRule();
	}
	
	//FeatureMapping:
	//	(srcFeatures+=SrcMappingFeature | srcClasses+=[ClassMatcher])+
	//	direction=Direction (trgFeatures+=TrgMappingFeature | trgClasses+=[ClassMatcher])+ ';';
	public FeatureMappingElements getFeatureMappingAccess() {
		return pFeatureMapping;
	}
	
	public ParserRule getFeatureMappingRule() {
		return getFeatureMappingAccess().getRule();
	}
	
	//MappingFeature:
	//	SrcMappingFeature | TrgMappingFeature;
	public MappingFeatureElements getMappingFeatureAccess() {
		return pMappingFeature;
	}
	
	public ParserRule getMappingFeatureRule() {
		return getMappingFeatureAccess().getRule();
	}
	
	//SrcMappingFeature:
	//	feature=[EStructuralFeature|FeatureAccess] | corr?='{' feature=[EStructuralFeature|FeatureAccess] ':'
	//	corrs+=Correspondence (',' corrs+=Correspondence)* '}';
	public SrcMappingFeatureElements getSrcMappingFeatureAccess() {
		return pSrcMappingFeature;
	}
	
	public ParserRule getSrcMappingFeatureRule() {
		return getSrcMappingFeatureAccess().getRule();
	}
	
	//TrgMappingFeature:
	//	feature=[EStructuralFeature|FeatureAccess] | corr?='{' feature=[EStructuralFeature|FeatureAccess] ':'
	//	corrs+=Correspondence (',' corrs+=Correspondence)* '}';
	public TrgMappingFeatureElements getTrgMappingFeatureAccess() {
		return pTrgMappingFeature;
	}
	
	public ParserRule getTrgMappingFeatureRule() {
		return getTrgMappingFeatureAccess().getRule();
	}
	
	//Correspondence:
	//	rule=[TransformationRule] ('[' matchers+=[ClassMatcher] (',' matchers+=[ClassMatcher])* ']')?;
	public CorrespondenceElements getCorrespondenceAccess() {
		return pCorrespondence;
	}
	
	public ParserRule getCorrespondenceRule() {
		return getCorrespondenceAccess().getRule();
	}
	
	//enum Direction:
	//	FWD='-->' | BWD='<--' | BX='<-->';
	public DirectionElements getDirectionAccess() {
		return eDirection;
	}
	
	public EnumRule getDirectionRule() {
		return getDirectionAccess().getRule();
	}
	
	//FeatureAccess:
	//	ID (=> '.' ID)+;
	public FeatureAccessElements getFeatureAccessAccess() {
		return pFeatureAccess;
	}
	
	public ParserRule getFeatureAccessRule() {
		return getFeatureAccessAccess().getRule();
	}
	
	//terminal ID:
	//	('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return tID;
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"'
	//	| "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return tSTRING;
	}
	
	//terminal WS:
	//	' '+;
	public TerminalRule getWSRule() {
		return tWS;
	}
	
	//terminal INDENTATION:
	//	('\r\n' | '\n' | '\r') '\t'*;
	public TerminalRule getINDENTATIONRule() {
		return tINDENTATION;
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* | ('\r\n' | '\n' | '\r') '\t'* '//' !('\n' | '\r')*;
	public TerminalRule getSL_COMMENTRule() {
		return tSL_COMMENT;
	}
	
	//terminal TAB_INDENTED_BLOCK_BEGIN:
	//	'synthetic:TAB_INDENTED_BLOCK_BEGIN';
	public TerminalRule getTAB_INDENTED_BLOCK_BEGINRule() {
		return tTAB_INDENTED_BLOCK_BEGIN;
	}
	
	//terminal TAB_INDENTED_BLOCK_END:
	//	'synthetic:TAB_INDENTED_BLOCK_END';
	public TerminalRule getTAB_INDENTED_BLOCK_ENDRule() {
		return tTAB_INDENTED_BLOCK_END;
	}
}
