/*
 * generated by Xtext 2.16.0
 */
package de.ubt.ai1.m2m.bxtenddsl.ui;

import com.google.inject.Injector;
import de.ubt.ai1.m2m.bxtenddsl.ui.internal.BxtenddslActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BXtendDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(BxtenddslActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		BxtenddslActivator activator = BxtenddslActivator.getInstance();
		return activator != null ? activator.getInjector(BxtenddslActivator.DE_UBT_AI1_M2M_BXTENDDSL_BXTENDDSL) : null;
	}

}
